ProvableHQ/leo

Cargo.lock, Cargo.toml, ast/Cargo.toml, compiler/Cargo.toml, gadgets/Cargo.toml, input/Cargo.toml, leo/commands/update.rs, leo/main.rs, linter/Cargo.toml, package/Cargo.toml, state/Cargo.toml, typed/Cargo.toml
=> Bump version and repair Leo update description

compiler/src/expression/circuit/static_access.rs
Fixes a bug where the static function of an imported circuit was invalid.
=> fix imported static access bug

ast/src/console/console_assert.rs, ast/src/console/console_error.rs, ast/src/console/console_function.rs, ast/src/console/console_function_call.rs, ast/src/console/mod.rs, compiler/src/console/assert.rs, compiler/src/console/console.rs, compiler/src/console/mod.rs, compiler/src/errors/console.rs, compiler/tests/console/mod.rs, typed/src/console/console_function.rs, typed/src/console/console_function_call.rs, typed/src/console/mod.rs
Fixes #274 
Adds license headers to missing files using https://github.com/kt3k/deno_license_checker
=> add missing license headers

leo/commands/build.rs, leo/commands/prove.rs
=> Update span message

compiler/tests/function/mod.rs, compiler/tests/function/return_tuple.leo, input/src/leo-input.pest
=> fix input tuple grammar rule

compiler/src/expression/expression.rs, compiler/tests/boolean/mod.rs, compiler/tests/boolean/not_mutable.leo
=> fix error using not operator on mutable boolean

leo/main.rs
Fixes leo help message. Found by @raychu86
=> update leo cli message

ast/src/circuits/circuit_member.rs, compiler/src/function/main_function.rs
Hotfix two cargo fmt blockers for release
=> Hotfix cargo fmt

.rusty-hook.toml, Cargo.lock, Cargo.toml, ast/Cargo.toml, compiler/Cargo.toml, input/Cargo.toml, package/Cargo.toml
Removes unused dependencies from Leo.
=> Removes unused dependencies from Leo

package/README.md, package/src/root/readme.rs
Update Leo package README with a simple build guide
=> Update Leo package README with a simple build guide

grammar/tests/serialization/expected_ast.json
The test is not run by the CI but run locally.
=> fix failing serialization test in grammar module

.github/workflows/ci.yml, .github/workflows/leo-clean.yml, .github/workflows/leo-init.yml, .github/workflows/leo-new.yml, leo/commands/watch.rs
=> Expand ci on leo commands

asg/src/expression/binary.rs, asg/src/lib.rs, asg/src/statement/assign.rs, asg/src/statement/conditional.rs
Basic fixes to satisfy clippy checks
=> cargo +nightly clippy

asg/src/expression/constant.rs, asg/tests/pass/group/mod.rs
=> [Feature] Implicit groups

LICENSE.md, SECURITY.md, asg/LICENSE.md, asg/README.md, ast/LICENSE.md, ast/README.md, compiler/LICENSE.md, gadgets/LICENSE.md, gadgets/README.md, grammar/LICENSE.md, grammar/README.md, imports/LICENSE.md, imports/README.md, input/LICENSE.md, input/README.md, linter/LICENSE.md, linter/README.md, package/LICENSE.md, package/README.md, state/LICENSE.md, state/README.md
Adds READMEs and LICENSEs to each Leo workspace member
=> Adds READMEs and LICENSEs to each Leo workspace member

asg/src/expression/binary.rs, asg/tests/pass/field/mod.rs, asg/tests/pass/group/mod.rs
=> Fix field/group addition

Cargo.lock, Cargo.toml, compiler/Cargo.toml, gadgets/Cargo.toml, state/Cargo.toml
=> [Dependencies] bump snarkvm module versions to 0.0.4

asg/src/scope.rs, asg/tests/pass/circuits/mod.rs
Fixes #642. Issues was that we didn't properly recursively resolve circuits when converting AST types -> ASG types
=> Fix circuit resolution

compiler/src/function/result/result.rs
This PR fixes failure to handle input-dependent branches. No tests added here since base case is covered, and this only occurs with production constraints. Should fix #535.
There is an additional issue not solved by this PR on branching on booleans from input.
=> Fix return type error for input-dependent branches

leo/commands/package/publish.rs, package/src/root/zip.rs
Fixes #637 
- now inputs are published to Aleo PM
- error json message is printed to user
We're unable to publish packages to PM, this PR fixes that.
TBD: CI for publishing
=> [CLI, PM] Inputs are now published with source code

compiler/src/value/field/field_type.rs, compiler/src/value/field/input.rs, compiler/src/value/group/targets/edwards_bls12.rs, compiler/src/value/mod.rs, compiler/tests/input_files/program_input/input/main_field.in, compiler/tests/input_files/program_input/input/main_group.in, compiler/tests/input_files/program_input/main_field.leo, compiler/tests/input_files/program_input/main_group.leo, compiler/tests/input_files/program_input/mod.rs
Allows -field values in input values, resolves #662. Also add tests for that and group - input values. Cleans up the re-written code used in a few places by adding a pub crate function. Depends on #626.
=> Bug 662 Fix

.github/workflows/release.yml
Fix build for windows 64 bit.
Run release workflow.
=> Fix build for windows 64 bit

grammar/abnf-grammar.md, grammar/abnf-grammar.txt
=> [ABNF] Make ** right-associative.

Cargo.lock, Cargo.toml, leo/logger.rs, leo/main.rs
Closes #609.
Closes #848.
This PR fixes ANSI coloring on Windows.
Tested by @damons on Windows machine.
=> [CLI] Adds colors to Windows cmd

asg/src/expression/call.rs, compiler/tests/circuits/mutable_call_immutable_context.leo
=> bug-fix-852

grammar/README.md, grammar/abnf-grammar.txt
The removed text is more of an internal discussion that actual documentation, so
it seems best to keep things slightly more concise.
[No changes to the grammar rules.]
[I'll merge some time tomorrow if all the CI tests pass and there are no objections to this change.]
=> [ABNF] Trim some documentation.

docs/rfc/001-initial-strings.md
This includes some explicit TODOs, but it should capture the consensus reached at Friday's design meeting. If anything important has been omitted, the omission is unintentional and should be remedied.
The intent is not to complete the TODOs as part of this PR, but rather merge this quickly into `master` via the usual review process and enable others to contribute more PRs to the documents, including replacing the TODOs with actual content. (Nonetheless, if obvious typos/mistakes are spotted in this PR, we could just fix them before merging.)
=> Add initial draft of string RFC.

docs/rfc/001-initial-strings.md
This PR adds code samples in *Characters* and *Strings* parts of our draft RFC. 
I used JS highlighting as its syntax is closest to ours.
=> [RFC Strings] Adds code samples to strings RFC

docs/rfc/001-initial-strings.md
Expand on a portion of the RFC.
=> [RFC] Add a clarification.

grammar/README.md, grammar/abnf-grammar.txt
I split this into multiple commits to facilitate review.
Closes #941.
Contributes to (the grammar part of) #949.
=> ABNF grammar updates for strings epic

docs/rfc/002-bounded-recursion.md
This is based on today's discussion at the compiler sync. The rationale for the
proposed name is explained in the added text. Open to change, as always.
=> [RFC] Add concrete proposal for compiler option.

ast/src/reducer/canonicalization.rs, compiler/tests/canonicalization/big_self_in_circuit_replacement.json, compiler/tests/canonicalization/big_self_in_circuit_replacement.leo, compiler/tests/canonicalization/string_transformation.json, compiler/tests/canonicalization/string_transformation.leo, tests/compiler/string/equality.leo
=> canonicalization fixes

docs/rfc/003-imports-stabilization.md
Work in progress. 
Closes #1053.
=> [WIP] Import Stabilization RFC

asg/src/error/mod.rs, asg/src/expression/tuple_init.rs, tests/compiler/tuples/access.leo, tests/expectations/compiler/compiler/tuples/access.leo.out
Closes #1044 fuzz bug. 
Tests included. 👍
=> Fixes tuple access

asg/src/expression/array_inline.rs, compiler/tests/type_inference/basic.json, compiler/tests/type_inference/basic.leo, tests/compiler/array/spread.leo, tests/expectations/compiler/compiler/array/spread.leo.out
=> array type inference bugs

.circleci/config.yml, Cargo.lock, Cargo.toml, compiler/Cargo.toml, compiler/src/value/group/targets/edwards_bls12.rs, state/Cargo.toml, synthesizer/Cargo.toml
Closes #1068 
Closes #1069
Closes #1070
Existing tests should pass.
=> Update to snarkvm 0.6.0

docs/rfc/005-countdown-loops.md
=> [RFC] Adds countdown loops RFC

ast/src/statements/console/formatted_string.rs
Fixes the display trait for FormatString
um, no tests but I think it's obvious to review:)
Nothing
=> hotfix:fix formatstring display trait

ast/src/statements/conditional.rs
1. Fixes the display trait for ConditionalStatement
um, no tests but I think it's obvious to review:)
Nothing
=> hotfix:ast:conditional statement display method

grammar/README.md, grammar/abnf-grammar.txt
(Thanks to @damirka for help in getting the markdown converter to work for this.)
=> Add some comments to the ABNF grammar and re-generate the markdown

docs/rfc/005-countdown-loops.md
=> [RFC] Add discussion of loop step and direction.

asg/src/expression/array_range_access.rs, tests/compiler/array/array_range_access_fail.leo, tests/compiler/array/input/array_range_access_fail.in, tests/expectations/compiler/compiler/array/array_range_access_fail.leo.out
Fixes #1149.
Also fixes some other unwraps while I'm in there.
=> [Bugfix] Fixes Rust Error for Invalid Slice

docs/rfc/005-countdown-loops.md
It may be easier to review each commit individually.
=> Incorporate recent discussions in countdown loops RFC

docs/rfc/002-bounded-recursion.md, docs/rfc/003-imports-stabilization.md, docs/rfc/004-integer-type-casts.md, docs/rfc/005-countdown-loops.md
The idea is:
- DRAFT when there are still decisions to make and consensus to reach.
- FINAL when consensus has been reached and it is ready to implement or being implemented.
- IMPLEMENTED when it has been implemented.
We could use other terms if desired. This is just one approach.
=> [RFC] Update some statuses.

compiler/src/statement/iteration/iteration.rs, tests/compiler/statements/all_loops.leo, tests/compiler/statements/reverse_loops.leo, tests/compiler/statements/reverse_one.leo, tests/expectations/compiler/compiler/statements/all_loops.leo.out, tests/expectations/compiler/compiler/statements/reverse_loops.leo.out, tests/expectations/compiler/compiler/statements/reverse_one.leo.out
=> fix reverse loop have to add range, which is always 1 for now

compiler/src/test.rs, parser/src/test.rs, tests/compiler/function/duplicate_definition_fail.leo, tests/expectations/compiler/compiler/function/duplicate_definition_fail.leo.out
Quick pr to fix the tests merged from #1201.
=> [Bugfix]Fix recently merged tests failing

parser/src/parser/file.rs, tests/compiler/import_local/import_weird_names_nested.leo, tests/compiler/import_local/local_imports/nested/c-d.leo, tests/expectations/compiler/compiler/import_local/import_weird_names_nested.leo.out
Closes #1239
We should allow accessing import folders with dashes.
Tests included.
None.
=> [Feature] Allow dashes in member access

docs/rfc/009-bit-byte-conversions.md
This is an attempt to collect and organize the information contained in various GitHub and Slack discussions into one coherent place for easy reference -- and update, if needed.
Please also review the last part of the 'Alternatives' section about naming. As always, when we add features, we should also keep in mind how they might fit within a broader consistent trajectory for the language.
=> [RFC] Add an RFC for bit and byte conversions.

imports/src/parser/import_parser.rs
Closes #1251.
Fail tests are currently not supported by test framework.
Already merged into #1119.
=> [Fix] Recursive imports 

.github/workflows/acl2.yml
As discussed, we don't want this CI to fail on each AST change, that's why we're making it a manual-triggered. 
Tested in a fork. Should work once merged to master.
=> [CI] Change ACL2 to manual trigger

docs/rfc/008-built-in-declarations.md
Updates RFC for built-ins since we have since discussed the way to implement them.
=> [RFC] Update RFC #8

asg/src/reducer/monoid/bool_and.rs, asg/src/statement/conditional.rs, ast-passes/src/canonicalization/canonicalizer.rs, compiler/src/option.rs, grammar/src/main.rs, leo/commands/build.rs, leo/config.rs
=> Misc cleanups of warnings & etc

docs/rfc/012-record-transaction-model.md
This RFC contains both some assertions and some questions.
Needed from the reviewers:
* Confirmation that the assertions are correct.
* Opinions on answers to the questions.
* Additional comments and observations, in particular any points that the current draft might have overlooked but that should be included in the discussion.
As with other PRs for initial RFC drafts, we do not need to wait for the RFC to be final before merging this PR into master. It can be finalized via additional PRs to master.
=> [RFC] Initial draft of record/transaction RFC.

docs/rfc/011-scalar-type-accesses-and-methods.md
No change in substance, just fixing a typo and updating some aspects.
=> [RFC] Some updates to the RFC for scalar methods.

compiler/src/expression/relational/eq.rs, errors/src/compiler/compiler_errors.rs, tests/compiler/array_without_size/compare_fail.leo, tests/expectations/compiler/compiler/array_without_size/compare_fail.leo.out
Closes #1356 found by @0rphon.
Tests are included.
=> [Fix] Throw an error when comparing arrays of different lengths 

docs/rfc/012-record-transaction-model.md
Based on discussions with Collin and the rest of the Leo team, these updates pick certain specific choices among the ones previously discussed, moving the others under alternatives.
Some choices are still pending.
(It may be easier to review one commit at a time.)
=> [RFC] Updates to record/transaction model

docs/rfc/001-initial-strings.md
No new text really, just more clearly separating what was decided and implemented vs. future idea.
=> [RFC] Clarify structure of character/string RFC

docs/rfc/002-bounded-recursion.md
No real change in content (aside from minor edits), but some text from the design section has been moved to background and some other text to future extensions.
=> [RFC] Clarify bounded recursion RFC

compiler/src/test.rs, errors/src/emitter/mod.rs, parser/src/parser/file.rs, tests/expectations/compiler/compiler/circuits/const_function_mut_fail.leo.out
- More error recovery more good. 😉 
- See changes in `tests/`.
- #1376
=> Parser: Recover on `mut self` and `mut PARAM: TYPE`

docs/rfc/011-scalar-type-accesses-and-methods.md, docs/rfc/013-const-functions.md
As @acoglio noticed we started to have divergence in RFCs between master and staging, this PR merges recent changes from master to staging.
=> [RFC] Merge RFC changes from master to staging

.github/dependabot.yml
Just a QOL to have dependabot point towards staging rather than master.
Might not actually work till this is merged to master?
=> Point dependabot to staging

asg/src/program/circuit.rs, asg/src/program/mod.rs, tests/compiler/aliases/circuit.leo, tests/expectations/compiler/compiler/aliases/circuit.leo.out
=> [Bugfix] circuit alias resolution fix

grammar/README.md, grammar/abnf-grammar.txt
This does not change the grammar.
=> [ABNF] Minor file layout improvement.

asg/src/accesses/circuit_access.rs, changelogs/template.md, changelogs/unreleased.md
Implements the changelog standard but broken into multiple files for readability and large files concerns.
Closes #1271.
Feel free to add anything I missed :).
=> [Impl] Changelog

ast/README.md
Probably more improvements to do, but this is a start.
=> [ast] Fix and update top-level documentation.

Cargo.lock, Cargo.toml, ast-passes/Cargo.toml, ast-passes/src/canonicalization/canonicalizer.rs, ast-passes/src/canonicalization/mod.rs, ast-passes/src/lib.rs, ast/src/reducer/mod.rs, ast/src/reducer/reconstructing_director.rs, ast/src/reducer/reconstructing_reducer.rs, compiler/Cargo.toml, compiler/src/lib.rs, leo/commands/build.rs, leo/main.rs, leo/tests/mod.rs
This PR is a mirror of #1608
I attempted to fix a spelling error in the branch name and it closed the previous PR.
My mistake @gluax
=> Migrate ast pass canonicalization

parser/examples/parser.rs
Fixes https://github.com/AleoHQ/leo/issues/1602.
=> Fix "parse error doesn't prevent AST output"

errors/README.md, span/src/span.rs, span/src/span_json.rs
=> [doc] Fix some typos and move a misplaced doc comment.

grammar/README.md, grammar/abnf-grammar.txt
=> fix console debug grammar discrep

docs/grammar/README.md, docs/grammar/abnf-grammar.txt
This does not change the grammar. It changes some text in the comments.
Some text was out of date; others were changed to make more clear.
=> [ABNF] Update some documentation

compiler/ast/src/chars/char_value.rs, compiler/parser/src/parser/context.rs, compiler/parser/src/parser/expression.rs, compiler/parser/src/parser/file.rs, compiler/parser/src/parser/statement.rs, compiler/parser/src/tokenizer/lexer.rs, leo/errors/src/parser/parser_errors.rs, tests/expectations/parser/parser/circuits/consts.leo.out, tests/expectations/parser/parser/circuits/consts_fail.leo.out, tests/expectations/parser/parser/circuits/types_fail.leo.out, tests/expectations/parser/parser/expression/literal/static_fail.leo.out, tests/expectations/parser/parser/expression/literal/string_fail.leo.out, tests/expectations/parser/parser/expression/unary/negate.leo.out, tests/expectations/parser/parser/program/q_eof.leo.out, tests/parser/circuits/consts.leo, tests/parser/circuits/consts_fail.leo, tests/parser/circuits/types_fail.leo
Closes #1635.
Closes #1636.
Closes #1671.
Closes #1692.
Closes #1694.
=> More Parser bugs Closing

tests/compiler/group/x_and_y.leo, tests/expectations/compiler/compiler/group/x_and_y.leo.out
=> [tests] fix (x,y)group test

build.rs
This PR fixes the license text checker on Windows by switching from byte comparison mode to string comparison instead; in addition, it has friendlier error messages now, e.g.:
```
--- stderr
thread 'main' panicked at 'Line 12 in file "./compiler/ast/src/access/associated_constant_access.rs" 
was expected to contain the license text "// GNU General Public License for more details.", 
but contains "// GNU General Public Licens for more details." instead! 
Consult the expected license text in ".resources/license_header"', build.rs:48:9
```
Any resulting performance change is not noticeable to the end user.
Fixes https://github.com/AleoHQ/leo/issues/1912
=> Make the license checker work on Windows too

.circleci/config.yml, leo/package/src/package.rs
=> Bump Rust version for CI

examples/token/.gitignore, leo/commands/run.rs
=> Minor cleanup

docs/grammar/abnf-grammar.txt
This is now part of the Leo compiler, so we need to update the grammar
accordingly.
=> [ABNF] Add inclusive loop bound.

examples/sorting/bubblesort_tuple/.gitignore, examples/sorting/bubblesort_tuple/README.md, examples/sorting/bubblesort_tuple/inputs/bubblesort_tuple.in, examples/sorting/bubblesort_tuple/program.json, examples/sorting/bubblesort_tuple/src/main.leo
Introduces a bubble sort example using tuples instead of arrays.
=> Example: Bubblesort with Tuples

docs/grammar/abnf-grammar.txt
This is for the upcoming [PR](https://github.com/AleoHQ/leo/pull/1963).
(We could wait to merge this PR until that PR is merged.)
=> [ABNF] Add the remainder operator.

leo/commands/build.rs, leo/commands/run.rs
=> Add offline option to Leo CLI

.circleci/config.yml, .circleci/leo-clean.sh, .circleci/leo-new.sh
`testnet3` is now a protected branch in Leo and requires these checks.
=> Update circle config.yml

leo/commands/build.rs, leo/commands/run.rs
This PR enables passing program inputs via CLI.
=> Enables inputs via CLI

compiler/passes/src/code_generation/visit_statements.rs
(Write your motivation here)
(Write your test plan here)
=> fix: Missing line break

compiler/passes/src/code_generation/visit_statements.rs
This PR fixes newlines associated with console statements in generated code.
=> [Fix] Newline in generated code

Cargo.lock, Cargo.toml, leo/commands/node.rs
Old
```
leo node start -- --nodeploy
```
New
```
leo node start --nodeploy
```
=> changes -- --nodeploy to --nodeploy

.circleci/config.yml, Cargo.lock, Cargo.toml, compiler/ast/Cargo.toml, compiler/compiler/Cargo.toml, compiler/parser/Cargo.toml, compiler/parser/src/parser/expression.rs, compiler/parser/src/parser/file.rs, compiler/passes/Cargo.toml, compiler/passes/src/type_checking/check_program.rs, compiler/span/Cargo.toml, docs/grammar/Cargo.toml, errors/Cargo.toml, leo/package/Cargo.toml
=> Release chores

examples/hackers-delight/ntzloops/src/main.leo, examples/hackers-delight/ntzseals/src/main.leo, examples/hackers-delight/ntzsearchtree/src/main.leo, examples/twoadicity/src/main.leo
Improve indentation on some examples.
=> [examples] improve indentation

.circleci/test-examples.sh, examples/tictactoe/README.md, examples/tictactoe/inputs/tictactoe.in, examples/tictactoe/program.json, examples/tictactoe/run.sh, examples/tictactoe/src/main.leo
=> Update tictactoe example.

.circleci/test-examples.sh, examples/broken_bank/.gitignore, examples/broken_bank/README.md, examples/broken_bank/inputs/bank.in, examples/broken_bank/program.json, examples/broken_bank/run.sh, examples/broken_bank/src/main.leo
=> Add `broken_bank` example.

.circleci/test-examples.sh, examples/auction/inputs/auction.in, examples/auction/program.json, examples/auction/run.sh, examples/auction/src/main.leo
=> Update auction example.

leo/commands/build.rs, leo/commands/deploy.rs, leo/commands/node.rs
Now prints 
```Compiled '{}' into Aleo instructions```
=> refactor cli output

examples/auction/README.md, examples/auction/src/main.leo, examples/broken_bank/README.md, examples/broken_bank/inputs/broken_bank.in, examples/broken_bank/program.json, examples/broken_bank/run.sh, examples/broken_bank/src/main.leo, examples/tictactoe/README.md, examples/tictactoe/inputs/tictactoe.in, examples/tictactoe/src/main.leo
=> Update READMEs for example.

docs/grammar/abnf-grammar.txt
Matches https://github.com/AleoHQ/leo/pull/2088.
=> [ABNF] Add `async` keyword.

compiler/passes/src/code_generation/visit_program.rs, tests/expectations/compiler/tuple/function_return_single_fail.out, tests/expectations/compiler/tuple/function_return_zero_fail.out
This PR updates code generation to target the ARC-003 specification for Aleo instructions.
=> Codegen for ARC-003

leo/package/src/source/main.rs
=> Fixes comment in file produced by `leo new`

compiler/compiler/src/compiler.rs, compiler/compiler/src/test.rs, compiler/passes/src/static_single_assignment/mod.rs, compiler/passes/src/static_single_assignment/rename_expression.rs, compiler/passes/src/static_single_assignment/rename_program.rs, compiler/passes/src/static_single_assignment/rename_statement.rs, compiler/passes/src/static_single_assignment/static_single_assigner.rs, compiler/passes/src/type_checking/check_expressions.rs, compiler/span/src/source_map.rs, tests/compiler/records/declaration.leo, tests/compiler/records/record_declaration_out_of_order.leo, tests/compiler/records/record_init_out_of_order.leo, tests/compiler/structs/struct_init_out_of_order.leo, tests/expectations/compiler/records/record_declaration_out_of_order.out, tests/expectations/compiler/records/record_init_out_of_order.out, tests/expectations/compiler/structs/struct_init_out_of_order.out, tests/test-framework/benches/leo_compiler.rs
=> Supports initializing `struct`s and `record`s with its members out of order.

compiler/ast/src/passes/reconstructor.rs, compiler/ast/src/passes/visitor.rs, compiler/ast/src/program/mod.rs, compiler/parser/src/parser/file.rs, compiler/passes/src/code_generation/visit_program.rs, compiler/passes/src/static_single_assignment/rename_program.rs, compiler/passes/src/type_checking/check_program.rs, compiler/passes/src/type_checking/checker.rs, errors/src/errors/type_checker/type_checker_error.rs
=> Disallows imports beyond one level of nesting.

README.md, docs/troubleshooting.md
=> Update install docs to include troubleshooting guide.

compiler/passes/src/code_generation/visit_expressions.rs, compiler/passes/src/code_generation/visit_statements.rs
=> Fixes code generation for ExpressionStatements

compiler/passes/src/code_generation/generator.rs, compiler/passes/src/code_generation/visit_program.rs, compiler/passes/src/function_inlining/inline_expression.rs, compiler/passes/src/function_inlining/inline_program.rs, compiler/passes/src/type_checking/check_expressions.rs, errors/src/errors/type_checker/type_checker_error.rs
=> Fixes issues with function inlining from imported programs.

compiler/compiler/src/compiler.rs, leo/commands/build.rs, tests/test-framework/benches/leo_compiler.rs, tests/test-framework/src/runner.rs
This PR adds code generation to the benchmarking framework.
To run benchmarks, see https://github.com/AleoHQ/leo/tree/testnet3/tests/test-framework#benchmarking.
=> [Test] Add support for benchmarking code generation.

Cargo.lock, Cargo.toml, compiler/ast/src/value/mod.rs
=> Update snarkVM to 0.9.15, aleo to 0.3.6

.all-contributorsrc, README.md
closes #2451 
closes #2452 
closes #2453
closes #2454
closes #2455
closes #2456
=> Add first row of contributors to README

Cargo.lock, tests/expectations/compiler/signature/signature.out, tests/expectations/execution/primitive_casts.out, tests/tests/compiler/signature/signature.leo
=> Add test to verify support of the ternary operator on signatures

.github/ISSUE_TEMPLATE/badge.md
Adds a contributor badge issue template so users don't have to fill in the information themselves.
=> Add a Contributor Badge Issue Template

examples/tictactoe/src/main.leo
This fixes a bug in examples/TicTacToe. Noticed this while playing around the TicTacToe example on play.leo-lang.org
=> Fixing a bug in examples/TicTacToe

Cargo.lock, Cargo.toml, tests/expectations/execution/eq.out, tests/expectations/execution/primitive_casts.out
=> [Dependencies] Update to snarkVM v0.15.2

.all-contributorsrc
=> [Documentation] Add a separate CONTRIBUTORS.md file.

Cargo.lock, Cargo.toml, tests/expectations/execution/eq.out, tests/expectations/execution/primitive_casts.out
=> [Dependencies] snarkVM 0.16.1

Cargo.lock, Cargo.toml, tests/test-framework/src/error.rs
=> [Dependencies] snarkVM 0.16.6

Cargo.lock, Cargo.toml, compiler/compiler/Cargo.toml, compiler/compiler/tests/compile.rs, compiler/parser/Cargo.toml, compiler/parser/src/parser/expression.rs, compiler/passes/Cargo.toml, compiler/passes/src/type_checking/check_expressions.rs, compiler/passes/src/type_checking/check_program.rs, compiler/passes/src/type_checking/checker.rs, leo/package/Cargo.toml, leo/package/src/package.rs, leo/package/src/root/env.rs
=> [Dependency] snarkVM 0.16.10

README.md
Updates and fixes broken Discord hyperlink.
=> Update & Fix Discord Hyperlink

Cargo.lock, Cargo.toml
=> [Dependency] Update to snarkvm 0.16.16

.github/ISSUE_TEMPLATE/config.yml
Read about some discord link hijackby a scammer  on twitter, so I'm checking if the discord links are the right ones.
One was corrected in #27006, but guess that one was forgotten. 
Better safe than sorry!
=> Updated discord link

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, leo/cli/commands/add.rs, leo/cli/commands/build.rs, leo/cli/helpers/context.rs, leo/package/Cargo.toml, utils/disassembler/Cargo.toml, utils/retriever/Cargo.toml, utils/retriever/src/retriever/mod.rs
=> [Refactor] Rename `disassembler` and `retriever` crates.

examples/tictactoe/src/main.leo
There is a typo in the logic of check_for_win function in tictactoe
Confirmed the logic.
=> fix: correct typos for win check in tic-tac-toe

compiler/ast/src/stub/function_stub.rs, tests/expectations/compiler/structs/external_struct_in_async_function.out, tests/tests/compiler/structs/external_struct_in_async_function.leo
=> [Fix] External struct in async function

leo/cli/commands/mod.rs, leo/cli/commands/query/mod.rs, leo/cli/commands/remove.rs
This PR fixes the API Endpoint for Testnet Beta.
=> [Fix] API endpoint

compiler/parser/src/tokenizer/mod.rs, compiler/parser/src/tokenizer/token.rs
This changes no functionality.
Clarify relation between tokens in the implementation and tokens in the ABNF grammar.
Group and characterize certain tokens more appropriately.
=> Improve some doc and layout.

compiler/parser/src/parser/file.rs, tests/expectations/parser/finalize/finalize_fail.out, tests/expectations/parser/functions/ident_token_fail.out, tests/expectations/parser/functions/test_keyword_fail.out, tests/expectations/parser/program/circuit_deprecated_fail.out, tests/expectations/parser/program/mapping_fail.out
This was missing a few alternatives.
=> Fix expected list in parser error.

tests/expectations/compiler/records/external_nested_record.out, tests/tests/compiler/records/external_nested_record.leo
=> Add nested external record test

.github/workflows/release.yml
=> [Fix] Introduces temporary changes to the release script, which remove compression for v2.

.github/workflows/release.yml
=> Fixes the release script for future releases.

Cargo.lock, Cargo.toml
=> Update snarkVM rev after the reset.

compiler/parser/src/parser/expression.rs, compiler/parser/src/parser/statement.rs, compiler/parser/src/parser/type_.rs, compiler/parser/src/tokenizer/token.rs
Also make a couple of minor code layout changes to order tokens in a clearer way.
=> Update and improve some parser documentation.

leo/cli/commands/account.rs
The `--seed` flag in the `leo account sign` command is insecure as `nonce`s in signatures are not intended to be seeded, reused, or shared. This PR removes that functionality to prevent anyone from accidentally using insecure functionality.
- Same fix for snarkOS cli: https://github.com/AleoNet/snarkOS/pull/3382
=> Remove --seed flag from account sign command

errors/src/errors/cli/cli_errors.rs, leo/cli/cli.rs, leo/cli/commands/account.rs, leo/cli/commands/example.rs, leo/cli/commands/new.rs, leo/cli/commands/query/mod.rs
=> Update API endpoint.

Cargo.lock, Cargo.toml
=> Update to the lastest snarkVM version.

compiler/passes/src/type_checking/checker.rs, tests/expectations/compiler/function/function_input_else_assignment.out, tests/tests/compiler/function/function_input_else_assignment.leo
=> Add function inputs to the type table.

.github/workflows/release.yml
=> [Fix] Rust image for Linux musl 

.github/workflows/release.yml
=> [Fix] Ensure that linux-musl is downloaded.

.github/workflows/release.yml
=> [Fix] Another attempt at ensuring the correct target is downloaded.

.github/workflows/release.yml
=> [Fix] Ensure toolchain is set.

.github/workflows/release.yml
=> [Fix] Musl CI

.github/workflows/release.yml
=> [Fix] Attempt to override GNU default toolchain

.github/workflows/release.yml
=> Use stable instead of x86_64

.github/workflows/release.yml
=> [Feat] Add tag dispatch to CI

.github/workflows/release.yml
=> [Fix] Checkout correctly and optionally select tag

.github/workflows/release.yml
=> [Fix] Temporarily force tag

Cargo.lock, Cargo.toml, leo/cli/commands/execute.rs
This PR updates the snarkvm rev to v1.1.0.
=> [Update] snarkVM rev to v1.1.0

.github/workflows/release.yml
=> Fix windows release CI.

leo/cli/commands/common/options.rs, leo/cli/commands/devnet/mod.rs
=> [Fix] Relax validation consensus height validation so that different devnets can be run.
