ProvableHQ/leo

package/src/root/zip.rs
package/src/source/directory.rs

Previously, `leo publish` allowed users to upload arbitrary files and file formats. This PR updates how `leo publish` selects files in the package to zip.
Currently `publish` only zips the `README.md` + `Leo.toml` files in the package root directory and all `.leo` files in the `src/` directory (including nested directories holding `.leo` files).
`leo publish` currently does not verify the contents of the package files.

Restrict zipped package files in `leo publish`

---

package/src/root/manifest.rs

This PR fixes the default license in the `leo.toml` file from "LICENSE-MIT" to "MIT".

Fix default license to MIT

---

leo/commands/new.rs

This PR updates the `leo new` command to generate a default `README.md` file in the same fashion as `leo init`.

Add README.md generation to `leo new`

---

leo/commands/publish.rs
package/src/root/manifest.rs

This PR updates the remote convention in the `leo.toml` file from 
``` remote = "{author}/{package_name}"```
to
```
[remote]
author = "{author}"
```
Additionally, the new implementation will automatically detect and replace the old remote formats.

Update leo.toml remote convention

---

leo/commands/add.rs
leo/errors/commands/add.rs

This PR adds support for remotes in the `leo add` cli command. Additionally it updates the description to specify "Aleo Package Manager"

Remote functionality in `leo add`

---

ast/src/expressions/array_initializer_expression.rs
ast/src/leo.pest
typed/src/common/spread_or_expression.rs

Fixes #199 
Removes unused `spread_or_expression` rule from array initializers.

Restrict pest grammar rule for array initializers

---

ast/src/leo.pest

Fixes #200 
Removes redundant parenthesis check in the conditional statement pest rule.

Simplify pest grammar rule for conditional statements

---

compiler/src/errors/value/integer.rs
compiler/src/value/integer/integer.rs
compiler/src/value/integer/macros.rs

Fixes #276 
Prevents signed integers from being used as array indices. Only unsigned integers are allowed.

Add compiler check for signed integer array access

---

compiler/src/constraints/constraints.rs

Improve readability of test output.
**before**
```
Test Running 3 tests
Test silly-sudoku::test_solve_fail ... ok
Test silly-sudoku::test_solve_pass ... ok
Test expected true, got true
Test silly-sudoku::test_solve_with_input ... ok
Finished Tests passed in 128 milliseconds. 3 passed; 0 failed;
```
**after**
```
Test Running 3 tests
Test silly-sudoku::test_solve_pass ... ok
Test silly-sudoku::test_solve_fail ... ok
Test expected true, got true
Test silly-sudoku::test_solve_with_input ... ok
Finished Tests passed in 111 milliseconds. 3 passed; 0 failed;
```

Add newline after each successful test run

---

ast/src/common/assignee.rs
ast/src/common/mod.rs
ast/src/common/self_keyword_or_identifier.rs
ast/src/leo.pest
typed/src/common/assignee.rs
typed/src/common/identifier.rs

Fixes #358 
Changes assignee rule in `leo.pest`.
Does not affect current Leo syntax.

make assignee rule more strict during pest parsing

---

.github/workflows/ci.yml
.github/workflows/release-tests.yml

Removes a legacy piece of CI where we load SSH keys for snarkOS. As these are now public, we no longer need them.

Updates CI to remove need for SSH keys as secrets

---

ast/benches/ast.rs
ast/benches/main.leo
ast/src/ast.rs

This PR changes the existing, trivial benchmark to a more advanced one, so that its results are more stable and at the same time more sensitive to future changes. I investigated the option of introducing more specialized AST benchmarks like in https://github.com/AleoHQ/leo/pull/388, but since there isn't much happening there other than the pest work, it would ultimately just be benchmarking `pest`.
In addition, the PR removes an unnecessary clone of the `Pairs` iterator by utilizing its [`peek`](https://docs.rs/pest/2.1.3/pest/iterators/struct.Pairs.html#method.peek) capabilities instead.

Change the AST benchmark to a more stable one, remove an unnecessary clone

---

ast/src/ast.rs
ast/tests/serialization/json.rs
compiler/src/expression/array/access.rs
compiler/src/expression/circuit/access.rs
compiler/src/expression/circuit/static_access.rs
compiler/src/expression/expression.rs
compiler/src/expression/function/function.rs
compiler/src/expression/tuple/access.rs
typed/benches/typed_ast.rs
typed/tests/serialization/json.rs

After the recent host of PRs there were a few small bits lost in conflicts; this PR includes them, making `cargo clippy --workspace --tests --examples --benches` clean.

A few post-merge cleanups

---

Cargo.lock
compiler/src/expression/function/function.rs
compiler/src/expression/logical/and.rs
compiler/src/expression/logical/or.rs
compiler/src/function/result/result.rs
compiler/src/statement/assign/array.rs
compiler/src/statement/assign/assign.rs
compiler/src/statement/assign/circuit_variable.rs
compiler/src/statement/assign/tuple.rs
compiler/src/statement/iteration/iteration.rs
compiler/src/value/address/address.rs
compiler/src/value/boolean/input.rs
compiler/src/value/field/input.rs
compiler/src/value/group/input.rs
compiler/src/value/integer/integer.rs
gadgets/Cargo.toml
gadgets/benches/integer_arithmetic.rs
gadgets/src/arithmetic/neg.rs
gadgets/src/bits/sign_extend.rs
gadgets/src/signed_integer/arithmetic/div.rs
gadgets/src/signed_integer/int_impl.rs
gadgets/src/signed_integer/relational/eq.rs
gadgets/src/signed_integer/utilities/alloc.rs
gadgets/src/signed_integer/utilities/select.rs
typed/src/expression.rs
typed/src/groups/group_value.rs
typed/src/statements/statement.rs
typed/src/types/type_.rs

The integer division tests (especially `test_int128_div`) are taking quite some time, so I started looking at ways of possibly improving the performance of arithmetic operations. This PR introduces a range of signed integer benchmarks modeled after their tests, and some performance-friendly changes mostly targeting avoidable allocations. There's also a handful of drive-by cleanup/refactoring commits. As usual, the commits are self-contained and their messages describe the specific changes.
One of the further possible improvements - and likely to have a big performance impact - would be to modify the `CondSelectGadget` trait so that the `first` and `second` arguments are `Cow<'a, Self>` as opposed to `&Self` in order to potentially avoid plenty of clones in case `cond` is a …

Arithmetic benchmarks and perf improvements

---

symbol-table/tests/mod.rs

Renames imported struct LeoAst -> Ast in symbol table tests

fix renamed struct in test

---

type-inference/src/objects/frame.rs

Bug found by @raychu86 .
When declaring a new array using a spread operator the type inference phase saves the array element type and not the array type.
```
let a: [u8] = [0; 4]; // Has type [u8]
let b = a[..]; // Has type u8, but should be type [u8]
```

fixes array spread declaration type bug

---

leo/errors/updater.rs
leo/updater.rs

Fixes #472
This PR fixes the error where the updater exits Leo CLI commands from executing when the updater fails to fetch the latest release version.

Fix early halting of leo commands due to updater checks

---

ast/src/functions/function.rs
ast/src/statements/block.rs
ast/src/statements/conditional_nested_or_end_statement.rs
ast/src/statements/conditional_statement.rs
ast/src/statements/mod.rs
ast/src/statements/statement.rs
compiler/src/function/function.rs
compiler/src/statement/block/block.rs
compiler/src/statement/block/mod.rs
compiler/src/statement/conditional/conditional.rs
compiler/src/statement/iteration/iteration.rs
compiler/src/statement/mod.rs
compiler/src/statement/statement.rs
core/src/packages/unstable/blake2s.rs
grammar/src/functions/function.rs
grammar/src/leo.pest
grammar/src/statements/block.rs
grammar/src/statements/conditional_statement.rs
grammar/src/statements/for_statement.rs
grammar/src/statements/mod.rs
grammar/tests/display.rs
grammar/tests/function.rs
grammar/tests/mod.rs
grammar/tests/serialization/expected_ast.json
type-inference/src/objects/frame.rs

Minor refactor to provide more useful type structure for scope analysis and reducers in general.
Note a minor grammar change, we now allow blocks with no statements in them for conditionals/for statements, was assumed that requiring statements was unintended.

Block AST node

---

compiler/src/value/value.rs
compiler/tests/mutability/let_mut_nested.leo
compiler/tests/mutability/mod.rs

Fixes #449 
Test added for #449 example

Fixes assignment of mutable variable to mutable variable

---

gadgets/src/signed_integer/arithmetic/mul.rs
gadgets/src/signed_integer/arithmetic/pow.rs

A few memory use improvements related to `mul` and `pow` operations; this PR was used as the basis for https://github.com/AleoHQ/snarkOS/pull/541.

Improve pow & mul performance

---

grammar/src/leo.pest

Closes #462 
Improves the `package_name` grammar rule in pest.
This PR does not change the current Leo ast.

Simplify Pest rule for package names

---

Cargo.lock
compiler/tests/array/mod.rs
compiler/tests/array/slice_lower.leo
grammar/src/common/range.rs
grammar/src/leo.pest

Fixes #408
Changes the grammar ast slightly.
Does not change the Leo ast.
`compiler/tests/array/slice_lower.leo`
```rust
function main() {
let arr: [u32; 9] = [0, 1, 2, 3, 4, 5, 6, 7, 8];
let expected: [u32; 2] = [0, 1];
let actual = arr[..2];     // Should produce [0, 1]
console.assert(expected == actual);
}
```

fix lower array slice bug

---

compiler/tests/array/spread.leo
type-inference/src/objects/frame.rs

Fixes a bug where the type inference pass did not correctly calculate the type of an array spread expression.
Test that a variable can be initialized with an array spread expression and that the expression returns the correct type.
Simply running the following code in a test would achieve this.
```rust
function main() {
let a: [u32; 2] = [1, 2];
let b: [u32; 3] = [...a, 3]; // This line should not fail.
console.assert(b == [1, 2, 3]);
}
```

Fix array spread type bug

---

compiler/src/statement/block/block.rs
compiler/src/statement/conditional/conditional.rs
compiler/src/statement/iteration/iteration.rs
compiler/src/statement/statement.rs
compiler/tests/circuits/mod.rs
compiler/tests/circuits/mut_self_variable_conditional.leo

Fixes a strange bug where accessing the `self` keyword in a new scope in a circuit function would fail.
Both conditional branches and for loops could previously not access or modify self.
```rust
function main() {
let mut f = Foo { a: 0u32 };
f.bar();
}
circuit Foo {
a: u32
function bar(mut self) {
if true {
self.a = 5u32; // Mutating a variable inside a conditional statement should work.
}
}
}
```

fix accessing self variable inside nested scope bug

---

compiler/src/compiler.rs
compiler/tests/compiler/main.leo
compiler/tests/compiler/mod.rs
compiler/tests/mod.rs

Fixes #454 
Add test ensuring parse_program and parse_program_from_string functionality matches.

Undeprecate parse_program_from_string

---

symbol-table/Cargo.toml
type-inference/Cargo.toml

Fixing a typo in the category slug in 2 Cargo.toml files

Fix typo in Cargo.toml category

---

Cargo.lock
Cargo.toml
compiler/Cargo.toml
core/Cargo.toml
gadgets/Cargo.toml
state/Cargo.toml

Update snarkVM deps to crates

---

grammar/src/leo.pest
grammar/tests/leo-samples/multiline.leo
grammar/tests/multiline.rs

Some multi line expressions and statements were impossible. Now almost every statement can be cut into multiple lines. 
```JS
function main() -> (
u32,
u32
) {
let a : u32 =
100; // hope nobody would do it, but they can 😆 
return (
1,
2
) // this was not possible
}
```
- Changed pest syntax.
- Also tested with pedersen-hash example.
- Added test with multiline samples - if this file parses, everything is correct.

Make Leo multiline 

---

examples/pedersen-hash/src/main.leo
type-inference/src/objects/frame.rs
type-inference/tests/arrays/index_implicit.leo
type-inference/tests/arrays/mod.rs
type-inference/tests/arrays/slice_implicit.leo
type-inference/tests/mod.rs
type-inference/tests/statements/array_loop_implicit.leo
type-inference/tests/statements/loop_implicit.leo
type-inference/tests/statements/mod.rs

Fixes #467 
Allows use of implicitly typed indices in Leo code.
```rust
let a = [0, 1, 2];
let b = a[0]; // Previously threw a type inference error
let c = a[0..1]; // Previously threw a type inference error
```
Tests use of implicit array indices.
Tests use of implicit array range indices.

Implement implicit u32 array indices

---

examples/pedersen-hash/src/main.leo
imports/src/parser/import_parser.rs
symbol-table/src/errors/symbol_table.rs
symbol-table/src/symbol_table.rs
symbol-table/tests/mod.rs
symbol-table/tests/symbol_table/import_alias.leo
symbol-table/tests/symbol_table/import_circuit_alias.leo
symbol-table/tests/symbol_table/import_function_alias.leo
symbol-table/tests/symbol_table/import_star.leo
symbol-table/tests/symbol_table/import_undefined.leo
symbol-table/tests/symbol_table/imports/bar.leo
symbol-table/tests/symbol_table/imports/foo.leo
symbol-table/tests/symbol_table/mod.rs
type-inference/src/objects/frame.rs
type-inference/tests/arrays/index_implicit.leo
type-inference/tests/arrays/mod.rs
type-inference/tests/arrays/slice_implicit.leo
type-inference/tests/mod.rs
type-inference/tests/statements/array_loop_implicit.leo
type-inference/tests/statements/loop_implicit.leo
type-inference/tests/statements/mod.rs

Fixes a bug where importing a circuit under an alias would cause an undefined user type error.
**src/foo.leo**
```rust
circuit Bar {
b: u8
}
```
**src/main.leo**
```rust
import foo.Bar as Baz;
function main() {
let z = Baz { b: 0u8 }; // Error.
}
```
* Tests for undefined import names.
* Tests that import star (*) correctly fetches all names.
* Tests that importing a circuit under an alias works. Also defines a circuit under the original name to verify.
* Tests that importing a function under an alias works. Also defines a function under the original name to verify.

Fix import type checking

---

compiler/src/expression/identifier/identifier.rs
leo/commands/run.rs

One panic can be folded in the error case of its enclosing `Result`, an `unwrap` call can be elided through pattern-matching reformulation.
Unrecoverable errors where they don't need to be.

Removes a panic

---

ast/src/expression/mod.rs
ast/src/expression/ternary.rs
compiler/src/expression/expression.rs
type-inference/src/objects/frame.rs

This PR renames the ConditionalExpression AST node to TernaryExpression to avoid confusion with ConditionalStatement.

Rename conditional expr to ternary

---

leo/main.rs

Closes #362 
Details:
- clap 2.X has an issue with adding empty line in the end
- proper fixing of this problem should be by updating to V3
Resources:
- 2018 issue with code example: https://github.com/clap-rs/clap/issues/1127#issuecomment-359790460
- https://gitmemory.com/issue/clap-rs/clap/1536/534784807

[cli] adds empty line for help command 

---

.github/workflows/leo-add-remove.yml

Copies #569
Reason: PRs from forks cannot use secrets.
---
Follow up on #551 and #560 
Added CI workflow for `leo login`, `leo add` and `leo remove` commands
> Requires `ALEO_PM_USERNAME` and `ALEO_PM_PASSWORD` to be set in secrets
More tests on CLI, improving developer experience

[CI] adds leo add and leo remove CI workflow

---

leo/commands/logout.rs
leo/commands/mod.rs
leo/config.rs
leo/main.rs

Closes #363.
Allows using different accounts. Also helps testing by trying out logged out state.
Will do in CI, one #579 is accepted, or vice versa.
CI can be added into #579, this PR should be accepted first then.

[CLI] Adds leo logout command

---

.github/workflows/leo-login-logout.yml
leo/commands/add.rs

Leo add could be done without logging into Aleo PM. So token check is removed. That simplifies process for newcomers, and helps on CI stage - no need to add credentials.
This PR includes changes to CI workflows: 
- login and logout have now their own workflow
- add, remove and clean are done without login
This PR finalizes work on previous tasks:
- #572 
- #560

[CLI, CI] Leo add does not require login

---

compiler/src/function/result/result.rs
compiler/tests/function/conditional_return.leo
compiler/tests/function/input/conditional_return.in
compiler/tests/function/mod.rs
compiler/tests/function/output/conditional_return.out

Fixes #535 .
Return path checking is provided by ASG, compiler return path checking is overzealous in a valid const branch evaluation due to use of `get_indicator_value` always being `false` if non-const.

Remove compiler return check

---

.github/workflows/leo-add-remove.yml
.github/workflows/leo-setup.yml
leo/commands/prove.rs
leo/commands/run.rs
leo/commands/setup.rs

Follow up on #521. As @damons suggested, I am attaching this PR for demonstration and proposal purposes.
This is a suggestion to add `--skip-key-check` flag to commands: setup, run and prove. Skipping this check would allow Leo developers to speed up these commands by skipping affine curve checks inside `snarkvm_algorithms`. Flag will only work when CLI command is run on already generated prove key (i.e. 2nd and 3rd and Nth time).
All commands output execution time and it is possible to see the results in CI workflow (leo-add-remove) for this PR. 
Includes changes to CI workflow, adds `leo setup` and `leo setup --skip-key-check`.

[CLI] Adds --skip-key-check option to setup, run and prove commands

---

asg/src/expression/call.rs
asg/src/expression/variable_ref.rs
asg/src/input.rs
asg/src/program/function.rs
asg/src/statement/assign.rs
asg/src/statement/definition.rs
asg/src/statement/iteration.rs
asg/src/type_.rs
asg/src/variable.rs
asg/tests/pass/function/mod.rs
asg/tests/pass/mutability/mod.rs
asg/tests/pass/mutability/swap.leo
ast/src/functions/input/function_input.rs
compiler/src/function/function.rs
compiler/src/function/main_function.rs
compiler/tests/mutability/mod.rs
compiler/tests/mutability/swap.leo
examples/pedersen-hash/src/main.leo
grammar/src/functions/input/function_input.rs
grammar/src/leo.pest

* To allow users to constrain function inputs to constant values only
* To pave a path forward for generics
* To allow easy, user-friendly const propagation at ASG level
Implementation for #605 .

[Feature] Const Function Arguments

---

compiler/tests/circuits/duplicate_name_context.leo
compiler/tests/circuits/mod.rs

Adding a test for duplicate name context that was resolved in #546.

duplicate name context test

---

compiler/tests/function/array_params_direct_call.leo
compiler/tests/function/mod.rs

Adding a test for bug #522, which was resolved by the asg.
Closes #522

fn call array params

---

leo/commands/build.rs

The `leo build` command serializes the circuit and stores it in a JSON file.
There is currently additional logic to deserialize the JSON file and the resulting circuit is unused.

[Bug] remove unused json deserialize logic

---

compiler/src/value/field/field_type.rs
compiler/tests/field/mod.rs
compiler/tests/field/negative_declaration.leo
compiler/tests/input_files/program_input/input/main_field.in
compiler/tests/input_files/program_input/main_field.leo
compiler/tests/input_files/program_input/mod.rs

Resolves #625. Logic used to do so is in check if first character of string to convert is a negative sign. If so remove first character convert from string to field, and then negate it on the leo side. If first character wasn't a negative sign, do the same as before.

Bug 625/fix negative fields not allowed

---

package/src/inputs/pairs.rs

Closes #660 
Any non-state or non-input file in program inputs folder causes test command to fail with error. This case is described in #660. Another case is also covered - files starting with dot (i.e. `.smth`) caused different error - now skipped.
Proposed behavior is skipping other files (with no warning/error) instead of erroring out. 
Tested locally, changes are small enough to see through

[CLI] Ignore non-input/state files in inputs folder when running tests

---

compiler/src/value/group/targets/edwards_bls12.rs
compiler/tests/group/mod.rs
compiler/tests/group/positive_and_negative.leo

Resolves #626. Allows a negative group outside of a pair as well as negative numbers inside a pair group. Waiting to see if the later was necessary in the feature discussion, but I assume it would be.

feature_626/negative-group-contstraints

---

asg/src/reducer/visitor_director.rs
compiler/src/expression/function/core_circuit.rs
compiler/src/function/function.rs
leo/commands/package/add.rs
leo/commands/package/clone.rs
leo/commands/package/publish.rs
leo/context.rs
leo/synthesizer/serialized_circuit.rs

Into the direct `Result` / `Option` combinator they correspond to, for concision / clarity.
Reviewed from automated suggestions generated from [comby-rust](https://github.com/huitseeker/comby-rust).

[easy] Simplifies a number of pattern-matches

---

leo/commands/build.rs
synthesizer/src/circuit_synthesizer.rs
synthesizer/src/serialized_circuit.rs

Profiling with `valgrind --tool=massif` reveals that `circuit_synthesizer::push_constraints` is responsible for rapid build-time memory use growth leading to out-of-memory issues even when objects are not retained. In order to fix this, the `CircuitSynthesizer` (specifically, its `ConstraintSystem` implementation) needs to keep track of when variables are being allocated and discard them when they go out of scope.
Below is a comparison of build-time memory use before:
and after these changes:
The test case used for profiling purposes is the one from https://github.com/AleoHQ/leo/issues/711.
Fixes https://github.com/AleoHQ/leo/issues/711.

Fix build-time OOMs by performing out-of-scope cleanups for CircuitSynthesizer objects

---

parser/examples/parser.rs

To install the parser do: `$ cargo install --path . --example parser` within the `<leo repo>/parser` directory. Executable is called `parser`.

Readd executable parser

---

leo/commands/build.rs
synthesizer/src/circuit_synthesizer.rs
synthesizer/src/serialized_circuit.rs

Since the `at`, `bt` and `ct` constraints are all aligned, i.e. created and used simultaneously, it makes sense to keep them together within another object, so that they are always handled at the same time and there's no confusion about things like determining the number of constraints or the index of a new one (i.e. currently just `at` is checked, which is valid, but not obvious).

introduce a helper ConstraintSet object

---

asg/tests/mod.rs
compiler/tests/console/mod.rs
compiler/tests/mod.rs

Just a `cargo clippy --workspace --all-targets` pass with Rust 1.50.

clippy: 1.50 lints

---

asg/src/error/mod.rs
asg/src/expression/array_access.rs
asg/src/expression/array_range_access.rs
asg/src/reducer/reconstructing_reducer.rs
compiler/src/errors/expression.rs
compiler/src/errors/statement.rs
compiler/src/expression/array/access.rs
compiler/src/expression/array/index.rs
compiler/src/expression/binary/binary.rs
compiler/src/expression/expression.rs
compiler/src/expression/tuple/access.rs
compiler/src/function/mut_target.rs
compiler/src/statement/assign/assignee.rs
compiler/src/statement/iteration/iteration.rs
compiler/src/statement/statement.rs
compiler/src/value/integer/integer.rs
compiler/tests/array/mod.rs
compiler/tests/function/array_params_direct_call.leo
examples/silly-sudoku/.gitignore
examples/silly-sudoku/Leo.toml
examples/silly-sudoku/README.md
examples/silly-sudoku/inputs/silly-sudoku.in
examples/silly-sudoku/inputs/silly-sudoku.state
examples/silly-sudoku/src/lib.leo
examples/silly-sudoku/src/main.leo

NOTE: based on #797.
Allow runtime array indexing. This PR does not add loop runtime indexing or array assignment runtime indexing.
Closes #746

Runtime array indexing

---

compiler/src/value/integer/integer.rs
compiler/src/value/integer/macros.rs

The code in branches can be deduplicated using a macro.

Deduplicate code in Integer::allocate_type

---

.cargo/config
.circleci/config.yml
.github/workflows/release.yml
Cargo.toml

- Adds a `noconfig` feature for release builds
- Updates CI to Rust v1.51

Adds a noconfig feature for release builds, updates CI to rust 1.51

---

grammar/abnf-grammar.md
grammar/abnf-grammar.txt

This still needed to be updated. The rules only supported self and mut self.
Also remove leftover reference to `function-call` in rule for `primary-expression`. (This was caught by running the grammar through the ACL2 validation.)
Also tweak some layout for consistency.
Also remove explicit author info from beginning of file.
Resolves #826.

[ABNF] Allow const self and other small fixes/improvements

---

grammar/abnf-grammar.md
grammar/abnf-grammar.txt

These commits, with one small exception described below, do not change any of the grammar rules, but just the documentation comments in the grammar file.
Some of the documentation had become obsolete after changing some rules, and needed to be updated. Some typos have been fixed. Some text has been clarified. Some discussions about alternative approaches, which were meant more for our internal use than for a published grammar, have been removed.
This has been done in separate commits to facilitate review.
The one exception, mentioned above, is the commit that fixes the rule for affine group literals: the change should have been part of #824, but apparently I failed to include it when I added the ABNF grammar commits to the PR. This omission is rectified by this commit.

[ABNF] Improve the documentation of the grammar and fix a rule

---

asg/src/error/mod.rs
asg/src/program/mod.rs
compiler/tests/function/duplicate_definition.leo
compiler/tests/function/mod.rs

Closes #829.
Described in the issue. 
Short: we don't fail if main is defined more than once and it causes return type mismatch for main function (if there's more than one main with different signature).
Contains a test for this scenario. Should fail on ASG level.

Adds error when function defined more than once

---

Cargo.lock
Cargo.toml
compiler/Cargo.toml
compiler/src/errors/value/integer.rs
compiler/src/statement/iteration/iteration.rs
compiler/src/value/address/address.rs
compiler/src/value/integer/integer.rs
compiler/src/value/integer/macros.rs
state/Cargo.toml
synthesizer/Cargo.toml

This PR fixes Leo's build with current snarkVM `master` branch. Once https://github.com/AleoHQ/snarkVM/pull/121 is merged and a new snarkVM is released, it only requires its crates' versions to be bumped in addition to these changes.

Align with snarkVM's Integer changes

---

package/src/package.rs

leo package names should allow numbers except for the first digit.
```rust
// Valid
"foo"
"foo-bar"
"foo-bar-baz"
"foo1"
"foo-1"
// Invalid
""
"-"
"-foo"
"foo--bar"
"foo*bar"
"foo,bar"
"1-foo"
```
Closes #833

Fix package name checks

---

ast/src/reducer/canonicalization.rs
compiler/tests/canonicalization/compound_assignment.json
compiler/tests/canonicalization/compound_assignment.leo

Fixes bugs #850, #851. In this instance it did not need to be reversed, and none of the current tests caught that. Added some better tests for that case.

Reversed-Accesses

---

package/src/root/zip.rs

Allows package publishing on Windows. 
How: paths were not escaped properly on Windows, library that we use (called `zip`) has deprecated method for that but reasons for deprecation are still not clear - they use this method in their examples with explicit `#[allow(deprecated)]`. And this method is recommended to solve Windows issue.
Tested by @damons and @0rphon on Windows machines.

[CLI] Fixes issue with `leo publish` on Windows

---

.circleci/leo-login-logout.sh
.circleci/leo-new.sh
leo/api.rs
leo/commands/init.rs
leo/commands/new.rs
leo/commands/package/login.rs
leo/commands/package/logout.rs
leo/commands/package/publish.rs
leo/config.rs
package/src/lib.rs
package/src/package.rs
package/src/root/manifest.rs
package/tests/initialize/initialize.rs

Closes #836.
Closes #847.
This PR adds few improvements to CLI.
If user is logged in and runs `leo new` or `leo init`, Leo.toml will contain his username by default.
```
leo login
leo new # Leo.toml has %username% in it
leo publish 
```
If user is not logged in or logged in after creating an empty package/program, nothing happens.
```
leo new
leo login # Leo.toml contains [AUTHOR] - default value
leo publish
```
So once user is logged in, substitution always happens and it's one time issue.
1. Previously we checked that token exists and that led to @0rphon catching "invalid token". Now running `leo login` over existing credentials will check that token is valid and not expired, and if it is not valid, local credentials are removed and user is asked to login again.
2. Also we now allow …

[CLI, Feature] Adds username substitution to manifest, improves login and error messages

---

README.md
grammar/README.md

Proposing to move the formatting note to the bottom of the markdown file.
This makes it more natural for readers.

Move format note to bottom of abnf grammar

---

grammar/README.md
grammar/abnf-grammar.txt

The documentation comments were out of date.
This was after changing the rules for format strings to be more restrictive, capturing all the requirements on containers without necessitating an extra-grammatical requirement.

[ABNF] Update documentation of format strings.

---

.circleci/config.yml
.circleci/leo-check-constraints.sh

Adds constraint number checking CI run.
Closes #805.
Described in #805.
We may consider using different approach and just add test within Leo instead of doing it on CI side. But on the other hand by using only CI tools we test application as a blackbox avoiding possible side effects.

[CI] Adds Pedersen Hash constraints check

---

leo/api.rs
leo/commands/package/publish.rs
leo/context.rs
leo/main.rs
leo/tests/mod.rs

This PR adds `APM_URL` ENV setting which allows specifying custom API backend for Leo CLI:
```bash
export APM_URL=https://api.aleo.pm/
leo add justice-league/u8u32
APM_URL=https://api.aleo.pm/ leo add justice-league/u8u32
```
This option is printed in help message only when calling global help:
```bash
leo help
leo --help
```
> With our current API it is impossible to check if URL is correct, so some responses for websites like https://google.com/ may cause confusion. We heavily rely on *404 Not Found* in our API, so when google or any other website respond with 404, error is interpreted like something is wrong with data sent to API.
We need this feature to support multiple backends and different APIs.
Open to any ideas on how to test this feature.
Tested manually.

[CLI] Allow setting custom API endpoint in ENV

---

compiler/src/compiler.rs
imports/src/parser/import_parser.rs
leo/main.rs

Closes #875.
Import path should be handled relatively to program source directory. 
Now all features using `--path` in Leo CLI are working.
So basically this is now possible:
```bash
leo build --path examples/silly-sudoku 
```
Includes tests which were blocked by this issue.

[CLI] Makes import path relative to program directory

---

grammar/abnf-grammar.txt

No change to the grammar rules.

[ABNF] Fix typo in documentation.

---

leo/api.rs
leo/commands/package/publish.rs

Closes #894.
Publish was the only route left after refactor. Now it's included into `leo/api` and features better error messages for non 200 responses. More details in #894.
Command itself didn't change, so passing CIs prove that it's the same command.

[CLI] leo publish now returns better error messages

---

leo/main.rs

The last drop into recent activity - tests for imports. Recent test improvements showed that some areas were not covered, and it's better to test as much as possible covering edge cases.
Adds test for `leo add` and `leo remove` with most of the possible options and arguments. 
This is test-only PR.

[CLI] Adds tests for imports

---

grammar/README.md
grammar/abnf-grammar.txt

(No changes to the actual rules.)
Explain better variable and constant declarations.
Leave one blank line between the rules for variable and constant declarations
(not necessary for ABNF, but consistent with the rest of the file and actually
expected by the ABNF-to-LaTeX converter).
Limit lines to 80 columns, by putting the rules for variable and constant
declarations over two lines each, with proper indentation.

[ABNF] Improve documentation and layout.

---

grammar/README.md
grammar/abnf-grammar.txt

The final semicolon was missing.
See https://developer.aleo.org/developer/language/imports.

[ABNF] Fix rule for import declarations.

---

docs/rfc/001-initial-strings.md

Strings RFC updates

---

grammar/abnf-grammar.txt

Explain the new syntax for circuit member variables.
Explain the tighter syntax for import declarations.
Keep lines to 80 columns max, so that they fit well in the figures in the LaTeX
document.
[No change to the grammar itself.]

[ABNF] Expand some doc and break some lines.

---

docs/rfc/001-initial-strings.md

This should reflect the latest consensus, after today's meeting.
There are no more TODOs in the document.
We can of course still change it if needed.
It occurred to me that, since empty arrays are disallowed, empty strings are disallowed too. This may seem surprising in general, but not if we think of Leo's treatment of arrays and thus of our initial representation of strings. Empty strings will be certainly supported by a future type of resizable strings.

[RFC] Update according to today's meeting.

---

docs/rfc/001-initial-strings.md

Rust allows `\u{1_____0__F____F______FF__________________________}` to mean `\u{10FFFF}`, in both char and string literals.  This PR, if accepted, would disallow this syntax in Leo char and string literals.
Make char and string literal syntax simpler.
Failure tests are covered by [aleohq/leo issue#1009](https://github.com/AleoHQ/leo/issues/1009).   That issue will need to be changed if this PR is not accepted (i.e., if we want to permit underbars in Unicode escapes).

RFC mod: Disallow underbars in \u{} escapes.

---

docs/rfc/001-initial-strings.md

I realized that we never updated the status of the strings RFC. We don't seem to have a designated enumeration of possible statuses of RFCs (e.g. draft, approved, etc.), but it looks like 'implemented' could be a good status for this.

Update status of strings RFC.

---

docs/rfc/002-bounded-recursion.md

This is an initial draft. As with the strings RFC, it does not have finalized before merging this. So at this stage approval of the PR just means 'okay to merge into master', without precluding the ability to edit it further (via more PRs).

Add RFC for bounded recursion.

---

.cargo/config
.github/workflows/release.yml

To cover Apple Silicon users of Aleo Studio, we need M1 builds. 
- Adds cross-compilation for `aarch64-apple-darwin` target;
- Compiles only `leo-lang` because it's the only binary that we need (optimize build time);
- Also closes #635 by keeping `target-cpu=native` only for `x64_86` builds for MacOS;
- Disables `grammar` package from workspace until we got dependency conflict resolved
Tested in a fork, release builds can be seen here: https://github.com/damirka/leo/releases/tag/v1.5.7

[Feature] Add M1 build, keep target-cpu=native only for MacOS builds

---

compiler/tests/canonicalization/string_transformation.json

Merging too fast caused a merge conflict in a test file. Quick pr to fix it.

quick pr to fix merge conflicts

---

docs/rfc/004-integer-type-casts.md

[RFC] Add initial RFC for type casts.

---

docs/rfc/003-imports-stabilization.md

Follow up after speaking with Howard. We'd want to have `proving system` and `curve` parameters inside Leo.toml to later match based on compatibility of ps and curves.

[RFC] Extending scope of the RFC to include proving system and curve

---

ast/src/errors/ast.rs
ast/src/lib.rs
compiler/src/compiler.rs
compiler/src/errors/compiler.rs
compiler/src/option.rs
compiler/tests/mod.rs
compiler/tests/test.rs
leo/commands/build.rs
leo/commands/test.rs

It goes towards feature #745,
Creates a new type of option the compiler uses: ProofOptions.
It generates the named JSON files in the `outputs` folder.
There are 4 new options for when running leo run/build/etc.
See the screenshot below for the new options, as well as the file names generated.

Ast Proof Generation In CLI

---

docs/rfc/004-integer-type-casts.md

Based on consensus within the Leo team, now the RFC prescribes the
value-preserving semantics. The discussion on value-changing semantics has been
moved to the 'Alternatives' section. Other text has been adapted and improved to
reflect the chosen approach (before, value-preserving and value-changing were
presented as two possible candidates for type casts).

[RFC] Update the type casts RFC.

---

compiler/src/compiler.rs

`"inital_ast.json"` --> `"initial_ast.json"`

fix typo in name of initial ast file

---

docs/rfc/005-countdown-loops.md

Discuss a possible extension to designate also the starting bound as inclusive
or exclusive, and discuss (a)symmetries and options.
Other minor edits.
This essentially incorporates https://github.com/AleoHQ/leo/issues/554#issuecomment-867229233 into the RFC.

[RFC] Extend the countdown loops RFC.

---

Cargo.lock
grammar/Cargo.toml
grammar/src/main.rs

Happy to announce that `abnf` crate is [patched to 0.12.0](https://github.com/duesee/abnf/pull/18), and our previous dependency conflicts have been resolved by that.

[Feature] Patch abnf to 0.12.0, return leo-abnf crate

---

asg/src/error/mod.rs
imports/src/errors/import_parser.rs
imports/src/parser/parse_symbol.rs
tests/compiler/import/imports/lib.leo
tests/compiler/import/string_import.leo

Closes #1180.
I also noticed that our test framework does not generate or maybe even test the ones in the import folder? It might be due to the wrong type of comments in the Leo files? Or do we not support importing through the test framework yet? Either way, we should file another bug to fix that.

[Bugfix] canonicalize imports

---

asg/src/error/mod.rs
asg/src/expression/ternary.rs
tests/compiler/statements/assign_ternary.leo
tests/expectations/compiler/compiler/statements/assign_ternary.leo.out

Closes #1176.
It seems we just never checked the types were the same at all, rather than a type inference bug.

[Bugfix] Ternary Type Check

---

compiler/src/value/address/address.rs
tests/compiler/address/branch.leo
tests/compiler/address/index.leo
tests/compiler/address/inputs/branch.in
tests/compiler/address/inputs/index.in
tests/expectations/compiler/compiler/address/branch.leo.out
tests/expectations/compiler/compiler/address/index.leo.out

This PR is aimed to fix #1161 and #1162. 
To do conditional selections of addresses, additional allocations for witnesses are needed. Such allocations use `alloc_helper`, which fails if the constraint system is in the setup mode.
This PR does the following: during the setup, the default address is being used as the placeholder.
I compiled Leo and ran it within Aleo Studio with the two programs in #1161 and #1162. It appears to run correctly.
Can someone see if the fuzzer is now satisfied with this change?
#1161 and #1162.

Fix the AssignmentMissing error involving non-constant addresses

---

grammar/README.md
grammar/abnf-grammar.txt

This just introduces a notion that is useful to shorten 'token, comment, or whitespace' to 'lexeme'. In particular, some parts of the formal specification will be more concise by referring to lexeme.
No change to the language. No lexer/parser change needed.

[ABNF] Add a rule for lexemes (i.e. lexical units).

---

.github/dependabot.yml
Cargo.lock
Cargo.toml
compiler/Cargo.toml
state/Cargo.toml
synthesizer/Cargo.toml

Update SnarkVM version to 0.7.6.
Clippy CI will pass once #1225 is merged.
CI tests should be enough.

Bump snarkvm to 0.7.6

---

grammar/README.md
grammar/abnf-grammar.txt

(May be easier to review one commit at a time, and skip the last one since it's just re-generating the markdown.)
This just renames `digit` to `decimal-digit`, to be more explicit, given that we also have `octal-digit` and `hexadecimal-digit`.

[ABNF] Rename digit => decimal-digit

---

grammar/README.md
grammar/abnf-grammar.txt

The test of the expression should have been a disjunctive expression. This was an oversight when the rules were written.

ABNF grammar fix

---

asg/src/expression/array_init.rs
asg/src/expression/array_inline.rs
asg/src/expression/array_range_access.rs
asg/src/expression/binary.rs
asg/src/expression/circuit_access.rs
asg/src/expression/tuple_access.rs
asg/src/expression/unary.rs
errors/src/asg/asg_errors.rs

Closes #1215.
Inspired by #1215, I reviewed most (or all) of the places where `unexpected_type` is thrown and fixed ordering.
Old tests should not fail.

[Bug] Fix ordering in unexpected_type error

---

docs/rfc/001-initial-strings.md
docs/rfc/002-bounded-recursion.md
docs/rfc/003-imports-stabilization.md
docs/rfc/004-integer-type-casts.md
docs/rfc/005-countdown-loops.md
docs/rfc/006-arrays-without-size.md
docs/rfc/007-type-aliases.md
docs/rfc/008-built-in-declarations.md
docs/rfc/009-bit-byte-conversions.md
docs/rfc/010-native-functions.md
docs/rfc/011-scalar-type-accesses-and-methods.md

The long list takes up space and is not that informative. The important information is that it was written internally (vs. community contributors, potentially). If anybody ever cares who actually wrote what, there's the git commit history for that.
This commit also auto-removes some trailing whitespace (no content change).

[RFC] Streamline RFC author information.

---

examples/hello-world/Leo.toml
examples/linear-regression/.gitignore
examples/linear-regression/Leo.toml
examples/linear-regression/README.md
examples/linear-regression/inputs/linear-regression.in
examples/linear-regression/inputs/linear-regression.state
examples/linear-regression/src/main.leo
examples/palindrome/.gitignore
examples/palindrome/Leo.toml
examples/palindrome/README.md
examples/palindrome/inputs/palindrome.in
examples/palindrome/inputs/palindrome.state
examples/palindrome/src/main.leo
examples/silly-sudoku/Leo.toml

We discussed it somewhere a while ago. 
Examples in the repo are a nice way to showcase the language to developers .
- Adds 2 more examples to the repo: `palindrome` and `linear-regression`. We have them on play.leo-lang.org, why not have them in the repo as well.
- Updates Leo manifests - adds target section following recent changes in import management

[Examples] Adds 2 more examples, updates manifests

---

grammar/README.md
grammar/abnf-grammar.txt

Extending array dimensions for types to allow underscore has the unintended
effect of allowing that also for expressions. This is not necessarily an error,
as the static semantics can rule out underscores from array expressions.
However, it is a simple syntactic constraint that is best captured by the
grammar.
This commit differentiate array dimensions for types and array dimensions for
expressions, using them in the appropriate places.

[ABNF] Improve rules for array expressions.

---

tests/expectations/compiler/compiler/array_without_size/length.leo.out
tests/expectations/compiler/compiler/array_without_size/length_fail.leo.out
tests/expectations/compiler/compiler/array_without_size/length_function.leo.out
tests/expectations/compiler/compiler/core/core_circuit_invalid.leo.out
tests/expectations/compiler/compiler/core/core_circuit_star_fail.leo.out
tests/expectations/compiler/compiler/core/core_package_invalid.leo.out
tests/expectations/compiler/compiler/core/core_unstable_package_invalid.leo.out
tests/expectations/parser/parser/expression/array_len.leo.out
tests/expectations/parser/parser/functions/param_array_unsized.leo.out
tests/expectations/parser/parser/statement/definition.leo.out
tests/parser/expression/array_len.leo
tests/parser/functions/param_array_unsized.leo
tests/parser/statement/definition.leo

- @gluax noticed that I missed parser tests for `.len()`, now they're added
- removes unstable core test expectations which are not used
- fixes failing CIs 
This PR is tests.

[Tests] Adds .len() parser tests, sanitizes some tests 

---

docs/rfc/009-bit-byte-conversions.md

This is as discussed with Jon.
This new version extends conversions from the integer values to all the scalar
values. It also describes instance and static methods instead of global
functions.
Material has also been re-arranged, as in other RFCs, to more clearly separate
the current decisions/implementations from alternatives and possible future
extensions.
NOTES:
* This is meant to include also the new content from https://github.com/AleoHQ/leo/pull/1409, which can be therefore thought of as part of this new PR.
* Some of the text in this new PR is based on a recent discussion on the snarkVM channel on Slack.
* The conversions of group elements may need to be revised (in both the RFC and the implementation) based on the aforementioned Slack discussions, but the RFC text in this PR should …

[RFC] Update the RFC on bit/byte conversions.

---

leo/commands/build.rs

Simple as never. Structopt uses docstrings to insert CLI help.
Closes #1437.

[Fix] Fixes command descriptions

---

grammar/README.md
grammar/abnf-grammar.txt

So they display well in the LLFS LaTeX.
Also add some markdown for two keywords in the comments.
Note: The generated README.md also includes a change from a previous commit, but that's just because that previous commit updated abnf-grammar.txt but not README.md.

[ABNF] Keep rules to 80 columns max.

---

test-framework/src/runner.rs

The test framework has the misleading output message: `failed {number_passing_tests}/{number_tests}`
Run the test framework with an incorrect test.

Fix test framework failed tests message

---

Cargo.lock

Updates cargo lock to point towards lastest snarkvm master commit as this fixes an issue due to an anyhow update.

updates snarkvm

---

grammar/README.md
grammar/abnf-grammar.txt

This was suggested by @bendyarm.
There is no need to require an end-of-line comment to terminate with an explicit
newline, which also prevents a file to end with and end-of-line comment without
a final newline. It suffices for an end-of-line comment to end when there is no
longer a non-newline character, which may happen either when there is a newline
character, or when the end of the file is reached.
This requires no change to the Leo lexer/parser, which is already implementing
the more relaxed rule.

[ABNF] Relax rule for end-of-line comments.

---

grammar/README.md
grammar/abnf-grammar.txt

This is more consistent with the terminology in the Leo Language Reference, and
also the comments in the grammar itself.

[ABNF] Rename newline => line-terminator

---

Cargo.lock
test-framework/Cargo.toml
test-framework/src/bin/tgc.rs

Closes #1578.
Tested locally, tgc is not a part of our test suite.

[Fix] Allows stdlib in tgc

---

leo/commands/build.rs

Fixes https://github.com/AleoHQ/leo/issues/1562
It's a upstream bug. See https://github.com/TeXitoi/structopt/issues/333
Run `leo -h` and see if it works
After the fix:
```
leo 1.5.3
The Aleo Team <hello@aleo.org>
Leo compiler and package manager
USAGE:
leo [FLAGS] [OPTIONS] [api] <SUBCOMMAND>
FLAGS:
-d               Print additional information for debugging
-h, --help       Prints help information
-q               Suppress CLI output
-V, --version    Prints version information
OPTIONS:
--path <path>    Optional path to Leo program root folder
ARGS:
<api>    Custom Aleo PM backend URL [env: APM_URL=]
SUBCOMMANDS:
build      Compile and build program command
clean      Clean outputs folder command
clone      Clone a package from Aleo Package Manager
deploy     Deploy Leo program to the …
```

Fix subcommand help messages

---

grammar/README.md
grammar/abnf-grammar.txt

Given that we have the rule
expression = conditional-expression
there seems to be no need for using conditional-expression in the 'else' branch
of a ternary expression, instead using the shorter expression.
This does not change the language or the abstract syntax.
If we merge this PR, we may want to also change the call of `parse_conditional_expression` to a call of `parse_expression` [here](https://github.com/AleoHQ/leo/blob/ede173ca7d6c4fca8e13b750cd0c4446a1e95ca4/parser/src/parser/expression.rs#L74) to keep things more aligned,  but it is not strictly necessary. Also, we may want to defer this until the parser migration to the testnet2 branch is completed.

[ABNF] Simplify a grammar rule.

---

parser/src/tokenizer/mod.rs

closes #1588
using a multi-byte character outside of a string now fails properly. ie:
```
function main () {
let 🦀: u8 = 0;
}
```
```
Error [EPAR0370000]: 🦀
--> D:\Work\leo-playground\src/main.leo:2:9
|
2 |     let 🦀: u8 = 0;
|         ^
```

fix character selection during `unexpected_token` error handling

---

ast-passes/src/canonicalization/canonicalizer.rs
ast/src/reducer/reconstructing_reducer.rs
ast/src/statements/definition/mod.rs
errors/src/ast/ast_errors.rs
parser/src/parser/statement.rs
tests/expectations/parser/parser/serialize/linear_regression.leo.out
tests/expectations/parser/parser/serialize/palindrome.leo.out
tests/expectations/parser/parser/serialize/pedersen_hash.leo.out
tests/expectations/parser/parser/statement/definition.leo.out

I did some code clean-up around array zero element checking.
Also did a check for 1 element type tuples. They are now disallowed.
Also adds a field to Definition statements to know if they are parened.
Then during canonicalization, this is disallowed if there is only one variable name.
Closes #1405.

[Fix] Disallow 1 element tuple types and variables

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

This "merges" the two previous slightly different notions of array type
dimensions and array expression dimension(s) into one notion of array
dimensions, in which the dimensions have to be natural numbers. (Previously,
array type dimensions were allowed to be unspecified (via underscores), while
array expression dimensions had to be specified.)
[Note that this PR is being made against the remove/unsized-array branch.]

[ABNF] Adapt ABNF to removal of unsized arrays.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

Types are now required in variable and constant declarations (including for loop
variables), and for literals (i.e. there are no longer untyped literals).
This is part of #1654.

[ABNF] Require types to avoid type inference.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

This does not change the grammar. It merely updates some text in the comments,
which shows a rule that was changed at some point but its copy in the comments
was not properly updated.
Thanks to @bendyarm for noticing this.

[ABNF] Update some documentation.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

This applies both to the rule name and to the terminology used for that, namely
for a non-empty sequence of decimal digits.
While 'natural' was meant to describe a natural number (i.e. a non-negative
integer: 0, 1, 2, ...), it is perhaps not a familiar term to many users.
On the other hand, 'integer', while often used in programming languages for this
kind of thing, is not ideal as integers may be negative.
Also, assuming type inference, a lone numeral like `17` may actually not denote
an integer number at all, because it may actually denote a group element if type
inference turns it into `17group`, and group elements are not integers.
All in all, 'numeral' seems like a good term, also according to its dictionary
definition. It is used in the Java grammar to denote this kind of thing, for …

Abnf natural to numeral

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

Given that arithmetic literals are now all typed in the grammar, we need
numerals to be listed as tokens. Otherwise, array dimensions and tuple indices
would not be tokens, but they must be.
(Just look at the change in `abnf-grammar.txt`. The change in `README.md` is larger because apparently I forgot to re-generate it as part of a previous commit.)

[ABNF] Add numerals to tokens.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

Also disallow 1-tuple array dimensions.
NOTES:
- The parser allow allows trailing commas everywhere, so it needs no change.
- Disallowing 1-tuple array dimensions is consistent with disallowing all the other kinds of 1-tuples, which was previously agreed. I think that the parser already disallows 1-tuple array dimensions (as of a relatively recent commit), but it would be good to double-check.
- There is a slight discrepancy regarding circuit member variables: the grammar allows commas and semicolons interchangeably, even mixing them in the same circuit declaration; while the parser accepts, in each single circuit declaration, either commas or semicolons (via two flags). Eventually we should pick one or the other, but the choice interacts with whether we want member function to be inside …

[ABNF] Allow trailing commas everywhere.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

These are needed to make parsing unambiguous. They require the test of a
conditional statement and the ending bound of a loop statement to not be or
start with a circuit expression.
Also update some other grammar documentation.
Closes #1627.
Closes #1632.

[ABNF] Add two extra-grammatical requirements.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

This does not change the language. It only renames two related rule names:
function-input => named-parameter
function-inputs => named-parameters
According to the new nomenclature, there are function parameters, which are self
parameters and named parameters: the nomenclature is clear and "symmetric".
The problem with the previous nomenclature is that both self and named
parameters are inputs, not just the named ones.

[ABNF] Improve some rule names.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

This does not change the language, but moves some expressions from postfix to
primary. Postfix expressions should have a recursive structure, which the moved
expressions do not have.
This change mirrors the organization of the parser of Leo written in ACL2, which
follows the naturally recursive structure of the language according to the
grammar.
Note that the current parser of Leo written in Rust, along with the Leo ASTs in
Rust, treats Leo functions as if they were expressions, but they are not
according to the ABNF grammar. (This is not necessarily a bug in the parser or
ASTs, if the expression ASTs are treated appropriately; but something we may
want to align to the ABNF grammar at some point -- separate topic).

[ABNF] Re-classify some expressions in the grammar.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

This mirrors, in pre-testnet3, the change in PR #1699 in testnet3.
Since in pre-testnet3 we have fewer kinds expressions, the category of postfix
expressions disappears altogether with this re-classification.

[ABNF] Re-classify function call expressions.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

The grammar allows any expression at parse time. The static semantics (type
checking) will enforce that it is a constant expression. This is no different
than in global and local constant declarations.
This addresses the grammar part of Issue #1635.

[ABNF] Allow any expression to initialize member constants.

---

tests/expectations/parser/parser/circuits/token_circuit_name.leo.out
tests/parser/circuits/token_circuit_name.leo

Regenerates `token-circuit-name-test` output file and changes the expectation to FAIL.

fix failing test

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

Expression statements were removed from the rule for statements, but the rule
for expression statements itself had not been removed. This commit fixes that.
Just look at the `abnf-grammar.txt` file (or at the first commit) for the actual change.
Apparently the `README.md` file had not been updated after a previous change to the grammar file.

[ABNF] Also remove rule for expression statements.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

This mirrors the structure of the rules for types, where there is an
`integer-type` consisting of `unsigned-type` and `signed-type`.
There is no change to the language.

[ABNF] Factor integer literals into a rule.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

This does not change the language. It just adds a rule to name binary
expressions explicitly. This makes the relation with ternary expressions
clearer, and as usual it explicates more terminology.
Just see `abnf-grammar.txt` diff. The `README.md` diff appears to include also a previous update.

[ABNF] Add rule for binary expressions.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

This is the (sub)grammar for input files. It is an initial draft, written based
on the Notion page 'Leo Input File Doc/Spec'. This should be compared with the
currently implemented parser of input (i.e. .in) files.
As the Leo Reference will describe (that part has not been written yet), the
input grammar is based on the lexical grammar, i.e. an input file consists of
tokens, comments, and whitespace. However, only some tokens (compared to the
syntactic grammar for Leo code files) are used, namely the ones reachable from
the `input-file` nonterminal.
Currently (i.e. im this initial version of Leo) `input-type` is (any) `type` and
`input-expression` is just a `literal`, but these may evolve as we extend the
language (e.g. we'll probably disallow circuit types and allow tuple and array …

[ABNF] Add (first draft of) input grammar.

---

docs/grammar/README.md
docs/grammar/abnf-grammar.txt

This does not change the language. It just factors things better and introduces
more nomenclature in the grammar.
As mentioned at today's sync, this is also motivated by improving the exposition in the Leo Reference book.

[ABNF] Add rule for numeric literals.

---

Cargo.lock
Cargo.toml
leo/main.rs

closes #1205 
This is a small PR that adds a custom panic hook to the leo compiler. This allows us to control the output in the event that a user encounters a critical bug while using leo. This is pretty standard practice in most compilers.
The function `set_panic_hook` now gets called at the beginning of `main` before anything in the compiler is run. If the binary was built in debug mode then this call does nothing and panics still operate exactly like normal, but if it was built in release mode then it registers a custom panic hook with some info about the environment and a link to [our bug template](https://github.com/AleoHQ/leo/issues/new?labels=bug,panic&template=bug.md&title=[Bug]) on github. I tried to model the panic message after the [rust internal panic …

Custom panic hook

---

tests/compiler/integers/i16/pow.leo
tests/compiler/integers/i8/pow.leo
tests/compiler/integers/u16/pow.leo
tests/compiler/integers/u8/pow.leo

(Note: I successfully ran `cargo test --all` on this PR, which I believe is all that's required right now.)
There were four test files, found by @bendyarm, that use end-of-line comments
instead of block comments as prescribed by the README.md.
This commit changes them to block comments, for consistency with the README.md,
and uniformity across the files.
There is clearly nothing wrong with supporting block comments (which apparently
the Rust implementation of the Leo test framework already does). However, just
supporting block comments slightly simplifies the processing of the Leo test
files on the ACL2 side, as we are building that processing right now.
We could support end-of-line comments on the ACL2 side as well if desired. But
it seems unnecessary and unimportant at least for now. …

[tests] Consistently use block comments.

---

leo/main.rs

while working on #1811 i realized that our panic hook prints to `stdout` instead of `stderr`. this is a super trivial change to fix that. just changes the hook's `println!` to `eprintln!`

Print panic hook in stderr

---

tests/compiler/integers/i128/inputs/pow.in
tests/compiler/integers/i128/pow_fail.leo
tests/compiler/integers/i32/inputs/pow.in
tests/compiler/integers/i32/pow_fail.leo
tests/compiler/integers/i64/inputs/pow.in
tests/compiler/integers/i64/pow.leo
tests/compiler/integers/i64/pow_fail.leo
tests/compiler/integers/u128/inputs/pow.in
tests/compiler/integers/u128/pow.leo
tests/compiler/integers/u32/inputs/pow.in
tests/compiler/integers/u32/pow.leo
tests/compiler/integers/u64/inputs/pow.in
tests/compiler/integers/u64/pow.leo
tests/expectations/compiler/compiler/integers/i128/pow_fail.leo.out
tests/expectations/compiler/compiler/integers/i32/pow_fail.leo.out
tests/expectations/compiler/compiler/integers/i64/pow_fail.leo.out
tests/expectations/compiler/compiler/integers/u128/pow.leo.out
tests/expectations/compiler/compiler/integers/u32/pow.leo.out
tests/expectations/compiler/compiler/integers/u64/pow.leo.out

Some of the larger integer `pow` compiler tests had no block comment header.  This PR adds those, and renames some files to be consistent, and adds some expectations files.
Although the test files are always supposed to have the header (according to `tests/README.md`), if the header is taken out, the test is just not run.  
It is possible that the `u32`, `u64`, and `u128` `pow.leo` files had their headers omitted for performance reasons.  For `testnet3` we are only compiling up to type checking now, and when we compile to the next IR the performance might not be as bad.  When I added the headers, I also added a comment about the possibility of future performance problems.
For the signed integer `pow` test cases, since all (except `i64`) were doing `a ** b` for `a` and `b` the same type, …

[tests] make integer pow tests consistent

---

tests/expectations/parser/parser/unreachable/postfix_pass.leo.out
tests/parser/unreachable/postfix_pass.leo

Since this test file is `namespace: ParseStatement`, it is easier to reuse if it just has statements in it, and not comments.  Moved the comment line into the YAML header and updated the expectation file.

[tests] move comment from body to yaml header

---

tests/parser/expression/literal/int_fail.leo

This change, suggested by @bendyarm, is perhaps a simpler solution to #1829.
By changing the category of these tests to 'expression', we get a failure both in the Rust parser of Leo (with or without the special handling of `0x`), and in the ACL2 parser of Leo.
Closes #1829.

[tests] Change category of the `0x` tests

---

tests/README.md
tests/test-framework/README.md
tests/test-framework/src/lib.rs

Updates the readme found in the `tests` directory. As well as adds a comprehensive overview of the test framework in the `tests/test-framework` directory readme.

[Docs] update test framework docs

---

docs/grammar/abnf-grammar.txt

In input and output files, literals are actually insufficient to represent the
most negative values of the signed integer types.
Given that we are likely to need richer forms of input and output expressions
anyways, at this point it seems best to allow any expression at the grammatical
level, and add static semantic requirements on the allowed expressions. As done
with all the other requirements, these will be stated in the Leo Reference,
formalized in ACL2, and enforced in the Leo compiler.

[ABNF] Relax input and output expressions.

---

Cargo.lock
Cargo.toml
compiler/parser/Cargo.toml
compiler/parser/examples/input_parser.rs
compiler/parser/examples/parser.rs
leo/commands/build.rs
leo/main.rs
tests/test-framework/Cargo.toml
tests/test-framework/src/bin/errcov.rs

simple pr that switches leo over to `clap` instead of `structopt` since `structopt` is now deprecated. the only real change to the code is that `AppSettings::ColoredHelp` is now set by default

replaced structopt with clap

---

docs/grammar/abnf-grammar.txt

Prohibit line terminators inside string literals. (This does not prohibit
escapes for line feed and/or carriage return; it prohibits actual line feeds and
carriage returns, which would break the string literal across lines.)
Explicate line terminators in block comments, so that an accurate line count can
be obtained more readily from the CSTs. (This is more relevant to the ACL2
formal development than to the Rust implementation, which does not have explicit
CSTs.)
Also reorder slightly some rules within the file.

[ABNF] Fix/improve handling of line terminators.

---

docs/grammar/abnf-grammar.txt

Since these are a method-like syntax for unary and binary operators (as in fact
these are represented as operators in the AST), the nomenclature 'operator call'
seems appropriate, at least for now. There is no need yet to introduce notions
of associated functions (and constants).
The rules explicitly distinguish between unary and binary ones, corresponding to
unary and binary operators. This lets us exclude right away calls with too many
arguments, and gives us a way to distinguish the two kinds.
A trailing comma is allowed at the end of the one argument of binary operator
calls, if one is really inclined to use it, just for syntactic consistency with
other calls (namely, function calls).

[ABNF] Add operator calls.

---

docs/grammar/abnf-grammar.txt

This adds shift (`<<` `>>`) and bitwise logical (`&` `|` `^`) operators.
Their precedence is between the additive and ordering operations, in this order
(higher to lower):
- ... others, to additive
- `<<` and `>>`
- `&`
- `|`
- `^`
- ... others, from ordering
This is consistent with Rust, but not with C and Java, both of which make the
bitwise logical operators lower-precedence than equalities.
Shift operations are left-associative, so `a >> b >> c` is like `(a >> b) >> c`, which makes sense.
Bitwise logical operators are left-associative, just to pick an order (they satisfy associativity).
The previous ABNF rule names for `conjunctive-expression` and
`disjunctive-expression` have been renamed to be more consistent with the newly
added ones. Also, the rule names "abbreviate" 'conjunctive' …

[ABNF] Add new operators.

---

docs/grammar/abnf-grammar.txt

Renames pre-existing (generic) function calls to 'free function calls', now that we are introducing a new kind of functions, namely (associated) static functions, distinguished from free (i.e. non-associated) functions.
Introduces notion of named type, as a type that has a name, which may be either a keyword (e.g. `u8`, `address`) or an identifier (e.g. `Pedersen64`).
Introduces nomenclature for identifiers used as expressions as being 'variables' or 'free constants'. The latter are distinguished from 'associated constants', which are a new kind of primary expression.
I went with 'component', rather than 'member', for the things that circuit types and values are made of. The reason is that 'member' seems to more generally refer to things tied to a type (cf. Java, or …

[ABNF] Add syntax for circuits and for associated constants and functions

---

docs/grammar/abnf-grammar.txt

`%xD` (Return character) was included in three of the rules when it was supposed to be omitted.

[abnf grammar] fix a few typos

---

docs/grammar/abnf-grammar.txt

This adds tuple types, tuple expressions (which build tuples from components),
and tuple component expressions (which access tuple components).
Based on previous discussions on this topic, 1-tuples are excluded. This
exclusion is done at the grammar level, since it is the kind of requirement that
is easily captured in a context-free grammar.

[ABNF] Add tuples.

---

Cargo.lock
Cargo.toml
compiler/ast/src/expressions/circuit_init.rs
compiler/parser/src/parser/expression.rs
compiler/passes/src/code_generation/visit_expressions.rs
examples/helloworld/main.aleo
examples/message/main.aleo
examples/message/src/main.leo
examples/token/main.aleo
examples/transfer/.gitignore
examples/transfer/README.md
examples/transfer/inputs/transfer.in
examples/transfer/main.aleo
examples/transfer/program.json
examples/transfer/src/main.leo
tests/expectations/compiler/compiler/circuits/inline.out
tests/expectations/compiler/compiler/circuits/member_variable.out
tests/expectations/compiler/compiler/records/init_expression.out
tests/expectations/compiler/compiler/records/init_expression_shorthand.out

token.leo
```ts
let t: Token = Token { balance: 100u64 };
```
token.aleo
```python
cast 100u64 into r0 as token.record;
```

Fixes codegen for circuit expressions

---

compiler/ast/src/input/input_ast.rs
compiler/ast/src/input/section.rs
examples/helloworld/imports/other.leo
examples/helloworld/inputs/helloworld.in
examples/helloworld/src/main.leo
leo/commands/run.rs
leo/package/src/package.rs

Adds support for executing specific programs in a Leo package.
main.leo
```ts
function main(a: u8) -> u8 {
return a + a;
}
function triple(b: u8) -> u8 {
return b + b + b;
}
```
foo.in
```toml
[main]
a: u8 = 2u8;
[triple]
b: u8 = 3u8;
```
Running
```bash
leo run main 
output = 4
```
```bash
leo run foo
output = 9
```

Leo run {program_name}

---

docs/grammar/abnf-grammar.txt

The identifier had been neglected.

[ABNF] Fix rule for circuit declarations.

---

docs/grammar/abnf-grammar.txt

It looks like these have been added to the compiler, so we should update the grammar to match.

[ABNF] Add compound assignments.

---

docs/grammar/abnf-grammar.txt

This is to match the recent introduction of the `@program` annotation for
external functions (i.e. functions that may be called externally, passing to
them inputs through the input files).
This PR adds not just that annotation, but a more general notion of annotation
as a new kind of token of the form `@<identifier>`, and with the ability to
precede each function declaration with zero or more such annotations.
The fact that it has been added as a token to the lexical grammar, means that
there cannot be any whitespace or comments between the `@` and the identifier.
If that is undesired, we can add it to the syntactic grammar instead, defining
an annotation as consisting of the (new) symbol token `@` followed by an
identifier token.
We can of course extend annotations with arguments at some …

[ABNF] Add annotations.

---

docs/grammar/abnf-grammar.txt

Add `console.assert_eq` and `console.assert_neq`.
Remove `console.log` and `console.error`.
Remove the format string grammar, since it was only used for console print
calls, which have been removed.
This matches #2023.

[ABNF] Revise console statements.

---

Cargo.lock
Cargo.toml
compiler/compiler/Cargo.toml
errors/src/errors/cli/cli_errors.rs
leo/commands/clean.rs
leo/commands/mod.rs
leo/commands/node.rs
leo/main.rs

```
leo node -h
Commands to operate a local development node
USAGE:
leo node [OPTIONS] <SUBCOMMAND>
OPTIONS:
-d                   Print additional information for debugging
-h, --help           Print help information
--path <PATH>    Optional path to Leo program root folder
-q                   Suppress CLI output
SUBCOMMANDS:
help     Print this message or the help of the given subcommand(s)
start    Starts a local development node
```

leo node cli command

---

README.md

Fix leo install method from source directly by `cargo install --path .`

Fix leo install method

---

docs/grammar/abnf-grammar.txt

The 2070 should have been 206A all along.

[ABNF] Fix typo in rule that excludes bidi chars.

---

docs/grammar/abnf-grammar.txt

Rename `end-of-line-comment` to the shorter `line-comment`, which is also consistent with the ABNF gramar of Aleo instructions.

[ABNF] Improve a rule name.

---

examples/hackers-delight/ntzdebruijn/src/main.leo

Fix typo so program can compile.  The other hackers-delight examples all compile and run fine.

fix typo in program name

---

compiler/span/src/source_map.rs
leo/package/src/package.rs

This PR fixes the check on the package name when invoking leo new <package_name>.
Package names are now checked to be valid identifiers, which should correspond to the requirements imposed by Aleo instructions.

Fix validation for package name.

---

compiler/passes/src/static_single_assignment/rename_program.rs

`IndexMap::remove()` doesn't preserve the insertion order ([doc](https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html#method.remove)). As a result, the order of struct members and struct initialize expressions will mismatch in aleo instructions. Although a little slower, `shift_remove()` preserves the order of the keys in the map.
`battleship` example was not working before this.

Preserve struct member order when reordering `owner` and `gates`

---

compiler/compiler/src/compiler.rs
compiler/compiler/src/test.rs

This PR fixes in issue with output AST snapshots for programs with imports.

Prepend program name to AST output file.

---

compiler/passes/src/flattening/flatten_statement.rs
compiler/passes/src/flattening/flattener.rs
tests/compiler/console/conditional_assert.leo
tests/expectations/compiler/console/conditional_assert.out

This PR,
- Fixes flattening for `console` statements such that it accounts for conditional statements. (See documentation in code for a detailed explanation).
- Minor refactor.

Fixes flattening for `console` statements.

---

.github/workflows/release.yml

Leo web playground is running on node:16-alpine. And Leo compiler Linux gnu build is missing libssl.so.3.
This PR builds it statically and fixes that issue.

Build Linux musl is required for leo web playground.

---

compiler/passes/src/type_checking/check_program.rs
compiler/passes/src/type_checking/check_statements.rs
compiler/passes/src/type_checking/checker.rs
tests/expectations/compiler/function/undefined_data_type_fail.out
tests/tests/compiler/function/undefined_data_type_fail.leo

[Fix] Fixes unwrapping panic when unwrapping `lookup_struct` in `ProgramVisitor::visit_function`

---

.github/workflows/ci.yml

```bash
Run brew update
error: Could not read 050b5490e7bb098f70f3de925431a24622f2d64c
fatal: revision walk setup failed
error: https://github.com/Homebrew/homebrew-cask did not send all necessary objects
```
GitHub actions CI failing due to broken `brew update` command on macos m1 platforms
Breaking in all current PRs. 
Example https://github.com/AleoHQ/leo/actions/runs/5463254559/jobs/9943707212?pr=2443
Removing `brew update` from CI as referenced in https://github.com/orgs/Homebrew/discussions/4612#discussioncomment-6356325

remove brew update command from ci

---

README.md

The abnf grammar is no longer stored in the leo repo. There is just a forwarding pointer to the grammars repo. This commit changes the link to go directly to the grammars repo.
(Write your motivation here)
(Write your test plan here)

change abnf grammar link

---

.github/workflows/release.yml
errors/src/errors/cli/cli_errors.rs
leo/cli/cli.rs
leo/cli/commands/example.rs
leo/cli/commands/mod.rs
leo/cli/commands/new.rs
leo/package/src/example.rs

```bash
Create a new Leo example package in a new directory
Usage: leo example [OPTIONS] <COMMAND>
Commands:
lottery    A public lottery program
tictactoe  A standard tic-tac-toe program
token      A transparent & shielded custom token program
help       Print this message or the help of the given subcommand(s)
```

implement leo example command for lottery, tictactoe, token

---

compiler/parser/src/parser/expression.rs
compiler/passes/src/code_generation/visit_expressions.rs
compiler/passes/src/type_checking/check_expressions.rs
tests/expectations/parser/functions/function_name_is_not_identifier.out
tests/tests/parser/functions/function_name_is_not_identifier.leo

This PR fixes #2521 by checking that function calls must lead with an identifier.
In the code linked in the above issue, the offending code is [here](https://gist.github.com/akalmykov/2a4d086f11142ed0083f74f7f32fdddf#file-main-aleo-L80)
```
assert(amount <= 1000u128 (10u128 ** token_info.decimals));
```

[Fix] Function calls must lead with an `Identifier.

---

README.md

Added back to top button in the readme file to go to the beginning of the page.
(Write your motivation here)
(Write your test plan here)

Added Back to Top button

---

examples/vote/build/main.aleo
examples/vote/run.sh
tests/test-framework/src/error.rs

Fix CircleCI errors. Which is test-examples in examples/vote/run.sh.
[Deprecate] Input files. #2630

Fix ci/circleci: test-examples

---

compiler/passes/src/code_generation/visit_program.rs

This PR fixes code generation to be compatible with `futures`.
Closes #3093.

[Fix] Codegen for futures.

---

.github/ISSUE_TEMPLATE/4_badge.md
.github/scripts/add_contributor.js
.github/workflows/add_contributor.yml

When a user submits a new issue, the bot first checks to see whether it is a request to be added as a contributor. If not, it quickly exits. The user will need to format the name of their request properly "Add XXXXX to contributors" in order for the action to run.
The GitHub Action ensures that:
- the person opening the issue requests that their own name be added to the README.
- there is a link to a GitHub repo in the issue body
- the user has starred the Leo repo
- the user is the author of the linked repo
- the linked repo contains a valid Leo application (by checking for presence of a `main.leo` file) 
Then, the GitHub action:
- creates a properly formatted PR to insert the user along with the requested badge and emoji into the README
- increments the Contributor Count section of the …

Feature - Add GitHub Action to add contributors to README

---

compiler/passes/src/code_generation/visit_expressions.rs
tests/expectations/compiler/array/array_initialization.out
tests/expectations/compiler/function/flatten_arrays.out

This PR fixes code generation for array init expressions.

Fix codegen for array init expressions

---

compiler/ast/src/types/array.rs

I resolved an issue parsing aleo code for generation of stubs from network-retrieval which was related to the array length property of `snarkvm_console_program::data_types::array_type::ArrayType<N>`. This type's length property is stored as `U32<N>`, not `PlaintextType<N>`.  `compiler > ast > src > types > array.rs` is attempting to utilize `NonNegativeNumber::from(array_type.length().to_string()),)`.  `NonNegativeNumber` expects pure numeric string values. 
See from `let value = usize::from_str(&string).unwrap();` that value is a `usize`.  In this case, the snarkVM value is parsed through `to_string()` and the `U32<N>::to_string` implementation appends `"u32"` to its value, resulting in the `InvalidInteger` `ParseIntError` error observed.
snarkVM relevant line:
``` …
```

[feat/stubs] Fix ParseIntError InvalidInteger in ast related to array type.

---

docs/rfc/000-rfc-format.md

There were several typos in the doc which need to be fixed.
.docs/rfc/00-rfc-format.md
No test is necessary as only docs is changed.

Fix several typos

---

Cargo.lock
Cargo.toml
leo/cli/commands/account.rs

close #10016 
When we run `leo account new` or `leo account import`, will display private key discreently on an alternate screen. See following pics

feat: support display private key discreetly

---

errors/src/errors/cli/cli_errors.rs
leo/cli/cli.rs
leo/cli/commands/account.rs

Signatures can be created/verified programmatically both from [AleoHQ/sdk](https://github.com/AleoHQ/sdk) (web-ui via [aleo.tools](https://aleo.tools/account)) and within [leo](https://developer.aleo.org/leo/language/#signatures) but not from the official leo or snarkOS CLIs.
This PR creates two straightforward commands for working with Aleo signatures:
- `leo account sign [--private-key-file <privateKeyFile>|--private-key <privateKey>] -m <message> -s [seed] [--raw]`
outputs an Aleo signature of the message, signed with the private key.
- `leo account verify -s <signature> -m <message> -a <address> [--raw]`
outputs `The signature is valid` or `The signature is invalid` if the signature is verified or invalid respectfully.
By default, all messages are snarkVM values so signatures are …

feat(cli): add sign and verify to the account subcommand

---

Cargo.lock
Cargo.toml
compiler/ast/src/expressions/literal.rs
compiler/parser/src/parser/expression.rs
compiler/parser/src/tokenizer/token.rs
compiler/passes/src/code_generation/visit_program.rs
compiler/passes/src/flattening/flatten_statement.rs
compiler/passes/src/type_checking/check_expressions.rs
compiler/passes/src/type_checking/checker.rs
compiler/span/src/symbol.rs
tests/expectations/compiler/address/special_address.out
tests/expectations/compiler/expression/network_id.out
tests/expectations/execution/metadata.out
tests/expectations/parser/expression/literal/address_parse.out
tests/expectations/parser/program/address_literal.out
tests/expectations/parser/program/network_id.out
tests/expectations/parser/program/special_address.out
tests/tests/compiler/address/special_address.leo
tests/tests/compiler/expression/network_id.leo
tests/tests/execution/metadata.leo
tests/tests/parser/expression/literal/address_parse.leo
tests/tests/parser/program/network_id.leo
tests/tests/parser/program/special_address.leo

Resolves #27912. Additionally, program name references are valid addresses. Example `let a: address = hello.aleo`.

[Feat] Add `network.id` and `self.address` opcodes

---

Cargo.lock
Cargo.toml
errors/src/errors/package/package_errors.rs
errors/src/errors/utils/util_errors.rs
leo/cli/cli.rs
leo/cli/commands/add.rs
leo/cli/commands/build.rs
leo/cli/commands/mod.rs
leo/cli/commands/query/block.rs
leo/cli/commands/query/committee.rs
leo/cli/commands/query/mempool.rs
leo/cli/commands/query/mod.rs
leo/cli/commands/query/peers.rs
leo/cli/commands/query/program.rs
leo/cli/commands/query/state_root.rs
leo/cli/commands/query/transaction.rs
leo/cli/commands/query/utils.rs
leo/cli/commands/remove.rs
leo/package/src/package.rs
utils/retriever/src/retriever/mod.rs

Resolves #27914. Additionally:
- `-c` flag to remove all previous dependencies
- Prevent adding local dependencies that have duplicate paths. (Choose to overwrite old dependency in favor of new one)
- Write the program that gets built instead of the generic `main.leo`

[Feat] Better `leo add` and `leo build` UX

---

Cargo.lock
Cargo.toml
leo/cli/commands/deploy.rs

The `build` prelude of `leo deploy used `BuildOptions::default()` which set `conditional_block_max_depth` to `0` causing builds to panic that contained conditionals in async function scope.

[Fix] `leo deploy` build panic

---

Cargo.lock
Cargo.toml
leo/cli/commands/deploy.rs
leo/cli/commands/execute.rs
utils/retriever/src/program_context/network_name.rs

This PR fixes the Leo CLI to allow deployments and executions on a local devnet.
For the `auction` example, the following commands work:
- `leo deploy --endpoint "http://0.0.0.0:3030"  --network testnet`
- `leo execute new --endpoint "http://0.0.0.0:3030"  --network testnet --broadcast --local`

[Fix] Deploy/execute on local testnet.

---

compiler/compiler/tests/compile.rs
compiler/compiler/tests/execute.rs
errors/src/errors/utils/util_errors.rs
leo/cli/commands/query/mod.rs
utils/disassembler/src/lib.rs
utils/retriever/src/retriever/mod.rs

Resolves #27977 and #27982. 
Details:
- Modularizes network retrievals. This way we are not maintaining two separate components for network retrievals, as previously we had both `leo query` and `retriever`.
- Previously network requests yielding responses like `Too Many Requests! Wait for 355256s` were being erroneously inserted into the `.aleo/registry` cache of network dependencies. This PR ensures that all fetched aleo programs are valid programs.

[Fix] Network retrieval refactor

---

compiler/ast/src/stub/function_stub.rs
compiler/passes/src/type_checking/checker.rs
tests/expectations/compiler/records/nested_record_as_function_io.out
tests/tests/compiler/records/nested_record_as_function_io.leo

Resolves #28070. The disassembler was erroneously using the locator name instead of locator resource as record name for nested stubs.

[Fix] Nested record build panic

---

Cargo.lock
compiler/passes/src/type_checking/check_program.rs
errors/src/errors/type_checker/type_checker_error.rs
tests/expectations/compiler/structs/empty_struct_fail.out
tests/tests/compiler/structs/empty_struct_fail.leo

This PR updates the type checker to return an informative error if a struct is declared without any members.
Closes https://github.com/AleoNet/snarkVM/issues/2058.

[Fix] Informative error on empty struct.

---

README.md

Add back in crates.io path once snarkvm has released a new version

[Fix] Recommend build from source in documentation

---

compiler/parser/src/parser/file.rs
compiler/parser/src/tokenizer/token.rs

This is only a documentation change.

Clarify ABNF vs. lexer/parser annotations.

---

leo/cli/commands/execute.rs

[Fix] Allow program names with or without the .aleo suffix in `leo execute`.

---

Cargo.lock
Cargo.toml

This PR updates the features for the `self_update` crate so that it supports the `deflate` format.

[Fix] Compression formats for `leo update`.

---

leo/cli/commands/deploy.rs

There is a duplicate ".aleo" present on the confirmation text during program deployment. This pr removes the duplicate ".aleo"
i.e. 
```
? Do you want to submit deployment of program `puzzle_arc_38.aleo.aleo` to network testnet via endpoint https://testnet.puzzle.online
```
I built leo locally and tested deploying a program.

[Fix] remove duplicate .aleo when deploying programs

---

examples/basic_bank/src/main.leo

There is a typo in the comment for the basic_bank example.

fix: update comment to clarify the account is stored as a hash

---

compiler/ast/src/types/type_.rs
compiler/passes/src/common/symbol_table/mod.rs
compiler/passes/src/flattening/flatten_expression.rs
compiler/passes/src/type_checking/check_expressions.rs
compiler/passes/src/type_checking/check_program.rs
compiler/passes/src/type_checking/checker.rs
tests/expectations/compiler/futures/future_in_tuple.out
tests/tests/compiler/futures/future_in_tuple.leo

Fixes #28312
Design choices:
- Using `eq_flat_relaxed` over `eq_flat` in TYC:
- ST makes sure that if we have multiple structs of the same name, then there is an error (before TYC starts). 
- `eq_flat` for strict equality, `eq_flat_relaxed` for relaxed equality. (When future is not explicit or struct matches but program origin is different).
- For [change](https://github.com/ProvableHQ/leo/blob/1d1d01aeeee42eeb3d9343fc4cd61c959a99589c/compiler/passes/src/type_checking/check_expressions.rs#L152) we could use `.eq_flat_relaxed` instead of `self.check_eq_types` but I thought it would be nice to have consistent usage of `check_eq_types` throughout TYC.

[Fix] Futures in Tuples

---

compiler/ast/src/types/type_.rs
errors/src/errors/type_checker/type_checker_error.rs

Consider this program:
```
// The 'leo_errors' program.
program leo_errors.aleo {
struct VoteAggregate {
proposal_id: field;
proposal_some: field;
}
struct SomeStruct {
proposal_id: boolean;
}
transition main() -> field {
let st:VoteAggregate = VoteAggregate{
proposal_id: 0field,
proposal_some: 0field,
};
let ss:SomeStruct = SomeStruct{
proposal_id: true,
};
return st.proposal_something;
}
}
```
The output of this program is:
After this PR :
Run the program above.

small error formatting improvements

---

errors/src/errors/utils/util_errors.rs
leo/cli/commands/mod.rs
utils/retriever/src/retriever/mod.rs

Update error messaging to account for redirects from APIs

---

compiler/parser/src/parser/file.rs
errors/src/errors/parser/parser_errors.rs
tests/expectations/parser/structs/comma_separators_fail.out
tests/expectations/parser/structs/only_comma_separators_fail.out
tests/tests/compiler/bugs/unknown_variable_fail.leo
tests/tests/compiler/console/assert.leo
tests/tests/compiler/expression/cast_fail.leo
tests/tests/compiler/finalize/mapping.leo
tests/tests/compiler/finalize/shadow_mapping_fail.leo
tests/tests/compiler/mappings/read_external_mapping.leo
tests/tests/compiler/structs/inline_fail.leo
tests/tests/compiler/structs/inline_member_fail.leo
tests/tests/compiler/structs/member_variable_fail.leo
tests/tests/compiler/structs/struct_function_namespace_conflict_fail.leo
tests/tests/parser/structs/comma_separators_fail.leo
tests/tests/parser/structs/only_comma_separators_fail.leo

Require comma separators (and nothing else) between struct members.

---

Cargo.toml

This results in a penalty to full compilation time, but a dramatic speedup to partial recompilation time.

Turn off LTO for dev and test builds.

---

Cargo.toml
leo/cli/commands/account.rs
leo/cli/commands/deploy.rs
leo/cli/commands/execute.rs

This feature is intended only to improve compiles times while developing Leo. It causes only testnet code to be compiled, leaving out canary and mainnet. Consequently compile times are much improved.

only_testnet feature.

---

leo/cli/cli.rs
leo/cli/commands/add.rs
leo/cli/commands/build.rs
leo/cli/commands/clean.rs
leo/cli/commands/deploy.rs
leo/cli/commands/example.rs
leo/cli/commands/execute.rs
leo/cli/commands/mod.rs
leo/cli/commands/new.rs
leo/cli/commands/query/block.rs
leo/cli/commands/query/committee.rs
leo/cli/commands/query/mempool.rs
leo/cli/commands/query/mod.rs
leo/cli/commands/query/peers.rs
leo/cli/commands/query/program.rs
leo/cli/commands/query/transaction.rs
leo/cli/commands/remove.rs
leo/cli/commands/run.rs
leo/cli/commands/update.rs

Two types of changes:
Many types that drive Parser from clap are renamed - this is because clap gives errors about ArgGroups sharing the same name otherwise, but mysteriously only when using the `dev` profile.
Some argument groups, in particular those under Query, had various conflicts that clap rejected, mostly when two arguments shared the same short name. Those have been resolved.

Fixes to clap CLI code.

---

tests/test-framework/src/error.rs

TOML can't serialize arrays as the top level type.
Some of our test cases have TOML arrays as expected output.
Thus sometimes failed tests will panic when trying to report
expected and found output. Instead, we now manually "serialize"
TOML arrays.

Don't panic when outputting TOML arrays in test failures.

---

README.md

This PR changes `developer.aleo.org` to `docs.leo-lang.org`.
Closes #28399

[Docs] Fix broken links

---

leo/cli/commands/mod.rs
utils/retriever/src/retriever/mod.rs

This PR updates the HTTP headers in network calls in the Leo CLI to more sensible defaults.

[Fix] Update HTTP headers in Leo CLI.

---

leo/cli/cli.rs
leo/cli/helpers/updater.rs

This PR addresses the comments in [this](https://github.com/ProvableHQ/leo/pull/28345) PR.
Shoutout to @ungaro for doing all the heavy lifting!
Closes #28345.
From the original PR.
Implemented an update notification system to keep users informed about new versions of the Leo CLI tool. 
This PR introduces the following enhancements to the update notification system:
1. **Conditional Update Checks**: The update notification system performs checks based on a time interval (currently set to once per day) or when forced, reducing unnecessary network requests. It writes the last check timestamp and latest version to cache files. This check runs on any command with arguments.
2. **Integration with Help and Version Commands**: Update notifications are also integrated into the help (`--help`) and …

[Feature] CLI Update Notification.

---

.github/workflows/release.yml

[Hotfix] Temporary for Linux musl release.

---

.github/workflows/release.yml

The Leo release CI can be quite problematic when there are updates to the underlying images that are no longer compatible.
Specifically, it's hard to adjust things on the fly when needed.
This PR requires that the release CI is explicitly triggered and gives an option to actually upload the release.
That way the Leo team can do a dry run, verify that everything builds, and trigger a live run.

[Fix] Improve Leo release CI

---

compiler/passes/src/type_checking/check_program.rs
compiler/passes/src/type_checking/checker.rs
errors/src/errors/type_checker/type_checker_error.rs
tests/expectations/compiler/futures/future_in_composite_fail.out
tests/tests/compiler/futures/future_in_composite_fail.leo

This already wouldn't work, but would either give misleading error messages or would compile to invalid bytecode.

Error on futures in arrays, structs, or mappings.

---

compiler/passes/src/common/graph/mod.rs
compiler/passes/src/static_single_assignment/rename_expression.rs
compiler/passes/src/static_single_assignment/rename_statement.rs
compiler/passes/src/symbol_table_creation/creator.rs
compiler/passes/src/type_checking/check_expressions.rs
compiler/passes/src/type_checking/check_statements.rs

remove redundant words and fix some typos in comment
No need.
(Write your test plan here)

chore: remove redundant words and fix some typos in comment

---

leo/cli/commands/deploy.rs
leo/cli/commands/execute.rs
leo/cli/commands/mod.rs
leo/cli/commands/query/mod.rs

This PR allows for execution fees to be determined by block height. If the height is greater than the `CONSENSUS_V2_HEIGHT` then the new (cheaper) fee calculation is used.

[Fix] Select fee based on consensus height

---

compiler/passes/src/type_checking/expression.rs
tests/expectations/compiler/bugs/b28614.out
tests/tests/compiler/bugs/b28614.leo

Closes #28608
Compare the types of `self.caller` and `self.signer` to `expected` when handling them in the type checker.
Added a single test that used to successfully compile but now fails with appropriate errors.

Fix a small type check error related to `MemberAccess` expressions

---

compiler/passes/src/type_checking/expression.rs
errors/src/errors/type_checker/type_checker_error.rs
tests/expectations/compiler/bugs/b28610.out
tests/expectations/compiler/finalize/get_or_incorrect_type_fail.out
tests/expectations/compiler/finalize/set_incorrect_type_fail.out
tests/tests/compiler/bugs/b28610.leo
tests/tests/compiler/finalize/get_or_incorrect_type_fail.leo
tests/tests/compiler/finalize/set_incorrect_type_fail.leo

Closes #28610
Emit an error when a record is instantiated in an async function context. We already do this for inputs and outputs of async functions.
Previously, we used to just emit invalid Aleo asm:
```console
Error [EUTL03710003]: Failed to parse the source file for `simple.aleo` into a valid Aleo program.
```
Now, we just emit a clean error:
Added a new test to check for the error

Disallow records from being instantiated in async functions

---

errors/README.md

Replaced the outdated or broken link to `span.rs` with a correct relative path (`../../compiler/span/src/span.rs`) within the repository. This ensures that contributors can easily navigate to the Span implementation from the documentation, regardless of their local or remote environment.

Update span.rs link in errors/README.md to use relative path

---

compiler/passes/src/type_checking/visitor.rs
tests/expectations/compiler/bugs/b28611.out
tests/tests/compiler/bugs/b28611.leo

Closes #28611
Looks like this was done properly for all other core functions. I went through them and they seem fine though they could probably use some more testing.
I opened #28618 - maybe we'll support tuples everywhere one day.
Added a single test that triggers the error.

Disallow tuples and maps in `Signature::verify`

---

compiler/passes/src/type_checking/program.rs
errors/src/errors/type_checker/type_checker_error.rs
tests/expectations/compiler/records/nested_record_4_fail.out
tests/expectations/compiler/symbols/illegal_names_fail.out
tests/expectations/compiler/symbols/illegal_names_in_library_fail.out
tests/tests/compiler/records/nested_record_4_fail.leo
tests/tests/compiler/symbols/illegal_names_fail.leo
tests/tests/compiler/symbols/illegal_names_in_library_fail.leo

Specifically, enforce the following rules:
1. A program ID must not contain the keyword "aleo" in the program name.
2. A record name must not contain the keyword "aleo".
3. Record names must not be prefixes of other record names.
4. Record entry names must not contain the keyword "aleo".

Disallow some illegal names

---

compiler/ast/src/statement/iteration.rs
compiler/parser/src/parser/statement.rs
compiler/passes/src/loop_unrolling/statement.rs
compiler/passes/src/loop_unrolling/visitor.rs
compiler/passes/src/type_checking/statement.rs
errors/src/errors/type_checker/type_checker_error.rs
tests/expectations/compiler/constants/constant_loop_bound_type_mismatch_fail.out
tests/expectations/compiler/type_inference/loop_iterators.out
tests/expectations/compiler/type_inference/loop_iterators_fail.out
tests/expectations/parser-statement/statement/iteration.out
tests/expectations/parser-statement/unreachable/define.out
tests/tests/compiler/type_inference/loop_iterators.leo
tests/tests/compiler/type_inference/loop_iterators_fail.leo
tests/tests/parser-statement/statement/iteration.leo

Closes #28631
This PR allows skipping the type annotation for loop iterators so that one can write
```
for i in 0u32..5u32 { .. }
```
- new parser and compiler tests

Type inference for loop iterators

---

leo/cli/commands/account.rs
leo/cli/commands/execute.rs
leo/cli/commands/mod.rs
leo/cli/commands/run.rs

This PR supports record ciphertexts in the CLI:
- as inputs to `leo execute`
- with `leo account decrypt`

[Feature] Support record ciphertexts in the CLI

---

leo/cli/commands/build.rs
leo/cli/commands/update.rs
leo/cli/helpers/updater.rs
leo/package/src/manifest.rs
leo/package/src/package.rs

This PR,
- supports release selection via `leo update -n <NAME>`
- `leo update` still updates to the latest release. If you select a version that does not have this feature, then you'll need to invoke `leo update` to get it again.
- `leo update -l` also lists the names of the releases, which is used in release selection. Some sample output:
```
> leo update -l
Leo
List of available versions for: aarch64-apple-darwin
Use the quoted name to select specific releases.
* 3.1.0 | 'v3.1.0'
* 3.0.0 | 'v3.0.0'
* 2.7.3 | 'v2.7.3'
* 2.7.2 | 'v2.7.2'
* 2.7.1 | 'v2.7.1'
* 2.7.0 | 'v2.7.0'
* 2.6.1 | 'v2.6.1'
```

[Feature] Support release selection via `leo update`.
